const categories=[['medication','Medication Log','✚'],['appointments','Appointments','▦'],['vitals','Vital Signs','♡'],['symptoms','Symptoms','⌁'],['meals','Meals & Hydration','◡'],['daily','Daily Care','☀'],['mood','Mood & Behavior','☺'],['sleep','Sleep','☾'],['incidents','Falls & Incidents','△'],['doctor','Doctor Notes','✎'],['expenses','Expenses','€'],['team','Care Team','♧'],['documents','Documents Log','▤']];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='kindred-care-v1';let state={profile:{name:'Parent',allergies:'',emergency:''},entries:[]},view='overview';
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&valid(saved))state=saved}catch{setTimeout(()=>toast('Your saved data could not be read. Import a backup to restore it.'),100)}
function valid(s){return s&&s.profile&&typeof s.profile.name==='string'&&typeof s.profile.allergies==='string'&&typeof s.profile.emergency==='string'&&Array.isArray(s.entries)&&s.entries.every(e=>e&&typeof e.id==='string'&&categories.some(c=>c[0]===e.category)&&typeof e.title==='string'&&typeof e.notes==='string'&&typeof e.author==='string'&&typeof e.date==='string'&&!isNaN(new Date(e.date).getTime())&&typeof e.handoff==='boolean'&&typeof e.done==='boolean'&&(e.amount===null||typeof e.amount==='number'&&Number.isFinite(e.amount)&&e.amount>=0)&&typeof e.unit==='string')&&new Set(s.entries.map(e=>e.id)).size===s.entries.length}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));return true}catch{toast('Local saving failed. Export your data to keep a copy.');return false}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4000)}
function localDate(d=new Date()){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function fmt(d){return new Date(d).toLocaleString('en-US',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}
function todayEntries(){const d=localDate().slice(0,10);return state.entries.filter(e=>e.date.slice(0,10)===d)}
function sorted(entries){return [...entries].sort((a,b)=>b.date.localeCompare(a.date))}
function nav(){const top=[['overview','Overview','▦'],['handoff','Caregiver Handoff','⇄']];$('#navigation').innerHTML=top.map(navItem).join('')+'<label class="journal-picker" for="journalNavigation">CARE JOURNAL<select id="journalNavigation" aria-label="Choose care journal category"><option value="">Choose a category</option>'+categories.map(c=>`<option value="${c[0]}" ${view===c[0]?'selected':''}>${c[1]}</option>`).join('')+'</select></label>'+'<div class="nav-divider">RESOURCES</div>'+[['emergency','Emergency Information','⚑'],['reports','Reports','▥']].map(navItem).join('');$('#sideName').textContent=state.profile.name}
function navItem(c){return `<button data-view="${c[0]}" class="${view===c[0]?'active':''}"><span class="nav-icon">${c[2]}</span>${c[1]}</button>`}
function entry(e){const c=categories.find(c=>c[0]===e.category);return `<div class="entry"><span class="entry-icon">${c[2]}</span><div class="entry-body"><div class="entry-title">${esc(e.title)}${e.done?' <span class="badge">Completed</span>':''}</div><p>${esc(e.notes)}${e.amount!==null?` · ${esc(e.amount)} ${esc(e.unit)}`:''}</p><small>${esc(c[1])} · ${esc(fmt(e.date))} · ${esc(e.author)}${e.handoff?' · For handoff':''}</small></div><div class="entry-actions">${e.category==='appointments'?`<button class="text-button" data-done="${esc(e.id)}" title="Change status">${e.done?'↶':'✓'}</button>`:''}<button class="text-button" data-edit="${esc(e.id)}" title="Edit">✎</button><button class="text-button" data-delete="${esc(e.id)}" title="Delete">×</button></div></div>`}
function empty(t='No entries yet. Add your first care update.'){return `<div class="empty"><span class="empty-symbol">♧</span>${t}</div>`}
function handoffText(){const entries=sorted(state.entries.filter(e=>e.handoff));return `Caregiver Handoff · ${state.profile.name}\nGenerated: ${new Date().toLocaleString('en-US')}\n\n`+(entries.length?entries.map(e=>`${fmt(e.date)} · ${e.title}\n${e.notes}${e.amount!==null?' · '+e.amount+' '+e.unit:''}\nRecorded by: ${e.author}`).join('\n\n'):'No entries have been marked for handoff.')}
function handoffCard(){return `<section class="card handoff"><div class="eyebrow">⇄ KEEPING CARE CONNECTED</div><h2>A smoother handoff. A calmer day.</h2><p>The important details for whoever takes over next.</p><div class="handoff-list">${esc(handoffText())}</div><div class="handoff-actions"><button class="secondary" data-copy>Copy summary ↗</button><button class="text-button" data-download>Download</button></div></section>`}
function render(){nav();const title=categories.find(c=>c[0]===view)?.[1]||({overview:'A little order. A lot more peace of mind.',handoff:'Caregiver Handoff',emergency:'Emergency Information',reports:'Care Reports'}[view]);$('#pageTitle').textContent=title;$('#breadcrumb').textContent=view==='overview'?'Overview':title;$('#today').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).toUpperCase();$('#pageSubtitle').textContent=view==='overview'?'Everything you need to care for your parent, all in one place.':`Care journal for ${state.profile.name}`;
if(view==='overview'){const today=todayEntries(),upcoming=state.entries.filter(e=>e.category==='appointments'&&!e.done&&new Date(e.date)>=new Date()).sort((a,b)=>a.date.localeCompare(b.date));$('#content').innerHTML=`<section class="welcome"><div><div class="eyebrow">THOUGHTFUL CARE, EVERY DAY</div><h2>A circle of care around ${esc(state.profile.name==='Parent'?'your loved ones':state.profile.name)}.</h2><p>A dose recorded. A visit planned. An update shared. The little things make a difference.</p></div><div class="welcome-art" aria-hidden="true">❧</div></section><div class="stats">${[['Medication today',(state.profile.doses||[]).filter(d=>d.scheduled.slice(0,10)===localDate().slice(0,10)&&d.status==='taken').length,'doses taken','✚'],['Upcoming appointments',upcoming.length,'visits planned','▦'],['Vital signs today',today.filter(e=>e.category==='vitals').length,'measurements recorded','♡'],['Today’s journal',today.length,'care updates','☀']].map(s=>`<div class="stat"><div class="stat-top">${s[0]}<span class="stat-icon">${s[3]}</span></div><strong>${s[1]}</strong><small>${s[2]}</small></div>`).join('')}</div><div class="grid"><div><section class="card"><div class="card-head"><h2>Today, one step at a time</h2><span class="badge">${today.length} entries</span></div>${sorted(today).map(entry).join('')||empty('Start the day with a small update.<br>Log medication, a meal, or an observation.')}</section><section class="card"><div class="card-head"><h2>Upcoming appointments</h2><button class="text-button" data-view="appointments">View all →</button></div>${upcoming.slice(0,3).map(entry).join('')||empty('No upcoming appointments. Plan the next doctor visit.')}</section></div><div>${handoffCard()}<section class="card"><div class="card-head"><h2>Quick add</h2><span class="badge">＋</span></div><div class="quick-grid">${categories.slice(0,6).map(c=>`<button class="quick" data-add="${c[0]}"><span>${c[2]}</span>${c[1]}</button>`).join('')}</div></section><p class="note">♡ Every entry helps your family stay connected to daily care.</p></div></div>`}
else if(view==='handoff')$('#content').innerHTML=handoffCard()+`<section class="card"><h2>How it works</h2><p class="note">Select “Include in caregiver handoff” when adding an entry. The summary includes all selected entries, with their dates and authors. Edit an entry and clear the checkbox when it is no longer relevant. Copy the summary to share it with your family.</p></section>`;
else if(view==='emergency')$('#content').innerHTML=`<section class="card"><div class="card-head"><h2>${esc(state.profile.name)}</h2><button class="secondary" data-profile>Edit profile</button></div><h2>Known allergies</h2><p class="emergency-box">${esc(state.profile.allergies||'No allergy information has been added.')}</p><h2>Contacts and important information</h2><p class="emergency-box">${esc(state.profile.emergency||'Add relevant contacts and information to the profile.')}</p></section>`;
else if(view==='reports'){$('#content').innerHTML=`<section class="card"><div class="card-head"><h2>Care report for ${esc(state.profile.name)}</h2><button class="secondary" data-print>Print / Save PDF</button></div><div class="toolbar"><label>From<input type="date" id="fromDate"></label><label>To<input type="date" id="toDate"></label></div><p class="note">Choose “Save as PDF” in your browser’s print dialog.</p><div id="reportEntries"></div></section>`;report()}
else{$('#content').innerHTML=`<section class="card"><div class="card-head"><h2>${esc(title)}</h2><span class="badge">${state.entries.filter(e=>e.category===view).length} entries</span></div><div class="toolbar"><input id="search" type="search" aria-label="Search the journal" placeholder="Search by title, details, or caregiver…"></div>${view==='documents'?'<p class="note">Keep document descriptions and storage locations here. Files are not uploaded.</p>':''}<div id="list"></div></section>`;list()}}
function list(){const q=($('#search')?.value||'').toLocaleLowerCase('en');$('#list').innerHTML=sorted(state.entries.filter(e=>e.category===view&&`${e.title} ${e.notes} ${e.author}`.toLocaleLowerCase('en').includes(q))).map(entry).join('')||empty()}
function report(){const from=$('#fromDate').value,to=$('#toDate').value;$('#reportEntries').innerHTML=sorted(state.entries.filter(e=>(!from||e.date.slice(0,10)>=from)&&(!to||e.date.slice(0,10)<=to))).map(entry).join('')||empty('No entries in the selected date range.')}
function extras(){const c=$('#categorySelect').value;$('#extraFields').innerHTML=c==='expenses'?'<div class="form-row"><label>Amount<input name="amount" type="number" min="0" step="0.01" required></label><label>Currency<select name="unit"><option>RON</option><option>EUR</option><option>USD</option></select></label></div>':''}
function openEntry(category='medication',existing){const f=$('#entryForm');f.reset();f.dataset.id=existing?.id||'';$('#categorySelect').innerHTML=categories.map(c=>`<option value="${c[0]}">${c[1]}</option>`).join('');f.elements.category.value=existing?.category||category;extras();f.elements.date.value=existing?.date||localDate();f.elements.author.value=existing?.author||state.entries.at(-1)?.author||'';if(existing){f.elements.title.value=existing.title;f.elements.notes.value=existing.notes;f.elements.handoff.checked=existing.handoff;if(existing.category==='expenses'){f.elements.amount.value=existing.amount;f.elements.unit.value=existing.unit}}$('#entryDialog').showModal()}
function openProfile(){const f=$('#profileForm');for(const k of ['name','allergies','emergency'])f.elements[k].value=state.profile[k];$('#profileDialog').showModal()}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render()}if(b.dataset.add)openEntry(b.dataset.add);if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.dataset.edit)openEntry(undefined,state.entries.find(e=>e.id===b.dataset.edit));if(b.dataset.delete&&confirm('Permanently delete this entry?')){state.entries=state.entries.filter(e=>e.id!==b.dataset.delete);persist();render()}if(b.dataset.done){const e=state.entries.find(e=>e.id===b.dataset.done);e.done=!e.done;persist();render()}if(b.hasAttribute('data-profile'))openProfile();if(b.hasAttribute('data-copy')){try{await navigator.clipboard.writeText(handoffText());toast('Summary copied.')}catch{download('caregiver-handoff.txt',handoffText(),'text/plain');toast('Summary downloaded and ready to share.')}}if(b.hasAttribute('data-download'))download('caregiver-handoff.txt',handoffText(),'text/plain');if(b.hasAttribute('data-print'))window.print()});
$('#addButton').onclick=()=>openEntry(categories.some(c=>c[0]===view)?view:'medication');$('#profileButton').onclick=openProfile;$('#categorySelect').onchange=extras;document.addEventListener('input',e=>{if(e.target.id==='search')list();if(['fromDate','toDate'].includes(e.target.id))report()});
$('#entryForm').onsubmit=e=>{e.preventDefault();const f=e.target,d=new FormData(f),id=f.dataset.id,old=state.entries.find(e=>e.id===id);const item={id:id||crypto.randomUUID(),category:d.get('category'),title:d.get('title').trim(),date:d.get('date'),author:d.get('author').trim(),notes:d.get('notes').trim(),handoff:d.has('handoff'),done:old?.done||false,amount:d.has('amount')?Number(d.get('amount')):null,unit:d.get('unit')||''};if(!item.title||!item.author){toast('Enter a title and the caregiver’s name.');return}if(id)state.entries[state.entries.findIndex(e=>e.id===id)]=item;else state.entries.push(item);const saved=persist();$('#entryDialog').close();render();if(saved)toast('Entry saved.')};
$('#profileForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);if(!d.get('name').trim())return;state.profile=Object.fromEntries(['name','allergies','emergency'].map(k=>[k,d.get(k).trim()]));const saved=persist();$('#profileDialog').close();render();if(saved)toast('Profile updated.')};
$('#exportButton').onclick=()=>download(`kindred-backup-${localDate().slice(0,10)}.json`,JSON.stringify(state,null,2),'application/json');$('#importButton').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10000000)throw Error();const imported=JSON.parse(await file.text());if(!valid(imported))throw Error();if(confirm(`Replace your local data with the profile “${imported.profile.name}” and ${imported.entries.length} entries? Export your current data first if you want to keep it.`)){state=imported;const saved=persist();render();if(saved)toast('Backup imported.')}}catch{toast('Invalid file. Choose a JSON backup exported from Kindred.')}e.target.value=''};render();

// Native dropdown supports mouse, touch, and keyboard navigation.
document.addEventListener('change',event=>{if(event.target.id!=='journalNavigation'||!categories.some(c=>c[0]===event.target.value))return;view=event.target.value;render();document.querySelector('#journalNavigation').focus();if(view==='documents'&&typeof loadPanels==='function')void loadPanels().catch(error=>toast(error.message));});
