/* Local-first care tools and protected server workflows. */
Care.upgrade(familyData);
let syncBase=structuredClone(familyData),mergeReview=null,pendingReason='Care record updated',installPrompt=null;
let historyRows=[],backupRows=[],documentRows=[],securityInfo=null,systemInfo=null;
const originalEnhancedRender=render,originalEnhancedNav=nav,originalCache=saveCache,originalPersist=persist,originalAccount=attachAccount;
function editingAllowed(){return currentUser?.role!=='viewer';}
function reasonForChange(reason){pendingReason=reason;}
saveCache=function(){const ok=originalCache();if(currentUser){try{const saved=JSON.parse(localStorage.getItem(cacheKey()));saved.base=syncBase;localStorage.setItem(cacheKey(),JSON.stringify(saved));localStorage.setItem('kindred-last-account',JSON.stringify({id:currentUser.id,name:currentUser.name,email:currentUser.email,role:currentUser.role}));}catch{}}return ok;};
attachAccount=async function(user){if(currentUser?.id!==user.id){historyRows=[];backupRows=[];documentRows=[];securityInfo=null;systemInfo=null;}const pendingCache=JSON.parse(localStorage.getItem('kindred-account-'+user.id)||'null');await originalAccount(user);Care.upgrade(familyData);syncBase=pendingCache?.pending&&pendingCache.base?pendingCache.base:structuredClone(familyData);if(!syncConflict)$('#syncConflict')?.remove();saveCache();};
let previousLocal=structuredClone(familyData);
function localChanges(before,after){const result=[];for(const p of after.profiles){const old=before.profiles.find(o=>o.id===p.id);if(!old)continue;for(const collection of ['entries','medications','doses','tasks','handoffs','shifts','questions']){const a=new Map((old[collection]||[]).map(r=>[r.id,r])),b=new Map((p[collection]||[]).map(r=>[r.id,r]));for(const id of new Set([...a.keys(),...b.keys()]))if(JSON.stringify(a.get(id))!==JSON.stringify(b.get(id)))result.push({id:Care.id(),profile:p.id,collection,record:id,before:a.get(id)||null,after:b.get(id)||null,action:!a.has(id)?'added':!b.has(id)?'deleted':'updated',actor:actor()||'Local caregiver',at:new Date().toISOString(),reason:pendingReason});}}return result;}
persist=function(){
  if(!editingAllowed()){toast(profile().isDemo?'Demo examples are read-only. Switch back to your care profile to add records.':'Your account has view-only access.');return false;}
  Care.upgrade(familyData);
  const changes=!currentUser?localChanges(previousLocal,familyData):[];
  const saved=originalPersist();if(!saved)return false;
  if(!currentUser){try{const rows=JSON.parse(localStorage.getItem('kindred-local-history')||'[]');rows.push(...changes);localStorage.setItem('kindred-local-history',JSON.stringify(rows.slice(-500)));}catch{toast('Care data saved, but this browser could not save the latest history entry.');}}
  previousLocal=structuredClone(familyData);return true;
};
pushChanges=async function(){
  if(!currentUser||syncBusy||syncConflict||!syncDirty||!navigator.onLine)return;
  syncBusy=true;
  try{
    while(syncDirty){const snapshot=structuredClone(familyData);const response=await api('state',{state:snapshot,revision:serverRevision,reason:pendingReason});serverRevision=response.revision;syncBase=snapshot;syncDirty=JSON.stringify(familyData)!==JSON.stringify(snapshot);saveCache();}syncStatus();pendingReason='Care record updated';
  }catch(error){
    if(error.status===409){
      const latest=await api('state');Care.upgrade(latest.state);const merged=Care.merge(syncBase,familyData,latest.state);
      if(!merged.conflicts.length){try{Care.validate(merged.state);familyData=merged.state;syncBase=latest.state;serverRevision=latest.revision;syncDirty=true;saveCache();setTimeout(pushChanges,0);}catch{syncConflict=true;showConflict();}}
      else{mergeReview={base:structuredClone(syncBase),local:structuredClone(familyData),remote:latest.state,revision:latest.revision,conflicts:merged.conflicts};syncConflict=true;showConflict();}
    }else if(error.status===403){syncConflict=true;showConflict();syncStatus('Access changed · review your saved copy');}
    else{syncStatus(error.status===401?'Reconnect to sync your saved changes':'Offline · changes saved on this device');}
  }finally{syncBusy=false;}
};
const oldConflict=showConflict;
showConflict=function(){oldConflict();if(mergeReview&&!$('#reviewMerge'))$('#syncConflict').insertAdjacentHTML('beforeend',' <button class="secondary" id="reviewMerge" data-review-merge>Review conflicting changes</button>');};
const baseRefresh=refreshFamily;
let reconnectingSession=false;
refreshFamily=async function(){
  if(currentUser&&!currentUser.csrf&&navigator.onLine&&!document.querySelector('dialog[open]')){
    if(reconnectingSession)return;reconnectingSession=true;
    try{await attachAccount(await api('me'));}catch{syncStatus('Reconnect to sync your saved changes');}finally{reconnectingSession=false;}return;
  }
  const prior=serverRevision;await baseRefresh();if(prior!==serverRevision&&!syncDirty)syncBase=structuredClone(familyData);
};
const accessSettings=()=>JSON.parse(localStorage.getItem('kindred-accessibility')||'{"scale":"normal","contrast":false}');
function applyAccessibility(){const pref=accessSettings();document.documentElement.dataset.textSize=pref.scale;document.documentElement.classList.toggle('high-contrast',pref.contrast);}
applyAccessibility();
nav=function(){originalEnhancedNav();$('#navigation').insertAdjacentHTML('beforeend',[['shifts','Caregiver Shifts','◷'],['consultation','Prepare a Visit','✎'],['history','History & Recovery','↶'],['settings','Settings & Security','⚙']].map(navItem).join(''));};
function card(title,body,button=''){return `<section class="card">${actions(title,button)}${body}</section>`;}
function shiftScreen(){const now=localDate();return card('Who is taking care today?',(profile().shifts||[]).sort((a,b)=>a.start.localeCompare(b.start)).map(s=>`<div class="entry"><span class="entry-icon">◷</span><div class="entry-body"><strong>${esc(s.caregiver)}</strong> ${s.start<=now&&s.end>=now?'<span class="badge">On duty now</span>':''}<p>${esc(fmt(s.start))} → ${esc(fmt(s.end))}<br>Backup: ${esc(s.backup||'Not assigned')}<br>${esc(s.notes)}</p></div><button class="text-button" data-edit-shift="${esc(s.id)}">Edit</button><button class="text-button" data-delete-shift="${esc(s.id)}">Remove</button></div>`).join('')||empty('Add a shift, a responsible caregiver, and a backup.'),'<button class="primary" data-new-shift>Add shift</button>')+card('Unclaimed and unfinished tasks',pendingTasks().map(t=>`<div class="entry"><div class="entry-body"><strong>${esc(t.title)}</strong><p>${esc(t.assignee||'Unassigned')} · ${esc(fmt(t.occurrence))}</p></div><button class="secondary" data-claim-task="${esc(t.id)}">Assign to me</button></div>`).join('')||empty('No outstanding tasks today.'));}
function questionsMarkup(){return (profile().questions||[]).map(q=>`<div class="entry"><div class="entry-body"><strong>${esc(q.title)}</strong><p>${esc(q.doctor||'No doctor selected')} ${esc(q.date)}<br>${esc(q.answer)}</p><span class="badge">${q.status==='answered'?'Answered':'To discuss'}</span></div><button class="text-button" data-edit-question="${esc(q.id)}">Edit / answer</button></div>`).join('')||empty('Write down questions before the appointment.');}
function trendChart(key,label,unit){const entries=profile().entries.filter(e=>Number.isFinite(e.vitals?.[key])).sort((a,b)=>a.date.localeCompare(b.date)).slice(-20);if(entries.length<2)return '';const values=entries.map(e=>e.vitals[key]),min=Math.min(...values),max=Math.max(...values),range=max-min||1;const points=values.map((v,i)=>`${35+i*430/(values.length-1)},${130-(v-min)*95/range}`);return `<figure class="trend-figure"><figcaption>${label} <small>${unit} · last ${values.length} readings</small></figcaption><svg role="img" aria-label="${esc(label)}: ${values[0]} to ${values.at(-1)} ${unit}" viewBox="0 0 500 165"><path d="M35 25V130H465" fill="none" stroke="#c5d3c9"/><polyline points="${points.join(' ')}" fill="none" stroke="#34765b" stroke-width="3"/>${points.map((xy,i)=>`<circle cx="${xy.split(',')[0]}" cy="${xy.split(',')[1]}" r="4" fill="#34765b"><title>${esc(fmt(entries[i].date))}: ${values[i]} ${unit}</title></circle>`).join('')}<text x="35" y="152">${esc(entries[0].date.slice(0,10))}</text><text x="465" y="152" text-anchor="end">${esc(entries.at(-1).date.slice(0,10))}</text><text x="8" y="25">${max}</text><text x="8" y="130">${min}</text></svg><details><summary>View readings</summary>${entries.map(e=>`<p>${esc(fmt(e.date))}: ${e.vitals[key]} ${unit}</p>`).join('')}</details></figure>`;}
function consultationScreen(){return card('Questions for the doctor',questionsMarkup(),'<button class="primary" data-new-question>Add a question</button>')+card('Measurement trends','<p class="note">Recorded measurements only, without interpretation or treatment advice.</p><div class="trend-grid">'+[['systolic','Systolic blood pressure','mmHg'],['diastolic','Diastolic blood pressure','mmHg'],['pulse','Pulse','bpm'],['temperature','Temperature','°C'],['oxygen','Oxygen saturation','%'],['weight','Weight','kg']].map(x=>trendChart(...x)).join('')+'</div><p class="note">Add at least two structured readings in Vital Signs to see a graph.</p>','<button class="secondary" data-view="reports">Open consultation report</button>');}
function historyScreen(){return card('Change history','<p class="note">'+(currentUser?'Server-recorded identity and timestamps. The latest 500 changes are shown.':'Local device history. Sign in through the server for an independently recorded audit trail.')+'</p><div id="historyRows">'+historyRows.filter(r=>r.profile===profile().id||!r.profile).map(r=>`<article class="history-record"><strong>${esc(r.action)} · ${esc(r.collection)}</strong><p>${esc(r.actor)} · ${esc(fmt(r.at))}<br>${esc(r.reason||'')}</p><details><summary>Before and after</summary><pre>${esc(JSON.stringify({before:r.before,after:r.after},null,2))}</pre></details>${r.action==='deleted'&&r.before&&(!currentUser||currentUser.role==='owner')?`<button class="secondary" data-restore-record="${esc(r.id)}">Restore deleted record</button>`:''}</article>`).join('')+'</div>','<button class="secondary" data-refresh-history>Refresh history</button>')+(currentUser?card('Automatic restore points','<p class="note">A snapshot is saved before each shared change. Restoring creates a new revision and keeps a record of the restoration. Only the family owner can restore.</p>'+backupRows.map(b=>`<div class="entry"><div class="entry-body"><strong>Revision ${b.revision}</strong><p>${esc(fmt(b.at))} · ${esc(b.actor)}</p></div>${currentUser.role==='owner'?`<button class="secondary" data-restore-backup="${b.id}">Restore</button>`:''}</div>`).join('')):'');}
function settingsScreen(){const pref=accessSettings();return card('Make Kindred comfortable to use',`<label>Text size<select id="textScale"><option value="normal" ${pref.scale==='normal'?'selected':''}>Standard</option><option value="large" ${pref.scale==='large'?'selected':''}>Large</option><option value="extra" ${pref.scale==='extra'?'selected':''}>Extra large</option></select></label><label class="checkbox"><input type="checkbox" id="highContrast" ${pref.contrast?'checked':''}> High contrast</label><p class="note">Dictation is available beside note fields when your browser supports it. You choose when the microphone starts. Your browser may use its speech service.</p><button class="secondary" data-install-app>Install / open installation help</button>`)+card('Notifications beyond the open page',`<p>Get reminders even when this page is closed. The local server and your computer must remain running and connected.</p><label class="checkbox"><input type="checkbox" id="escalatePush"> Also notify me when a medication assigned to me remains unrecorded for an hour</label><div class="toolbar"><button class="primary" data-enable-push ${currentUser?'':'disabled'}>Enable background reminders</button><button class="secondary" data-disable-push ${currentUser?'':'disabled'}>Disable my background reminders</button></div><p class="note">Sign in first. Browser support and notification permission are required. This is not an emergency alert system.</p>`)+card('Care time zone',field('Use the same care time zone on all caregiver devices','careTimezone','text',profile().timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,'id="careTimezone"')+'<button class="secondary" data-save-zone>Save time zone</button><p class="note">Server reminders use this time zone. The journal and forms use the device’s local time; keep it aligned with the care time zone.</p>')+(currentUser?card('Account security',`<p>Authenticator: <strong>${securityInfo?.enabled?'Enabled':'Not enabled'}</strong> · Unused recovery codes: ${securityInfo?.recoveryCodes??'—'}</p><div class="settings-actions"><button class="secondary" data-twofactor>${securityInfo?.enabled?'Disable':'Set up'} two-step sign-in</button><button class="secondary" data-recovery-codes>Create recovery codes</button><button class="secondary" data-change-password>Change password</button></div><p class="note">Store recovery codes privately. A recovery code can reset your password and authenticator if you lose access.</p>`):card('Account recovery','<button class="secondary" data-reset-password>Reset password with a recovery code</button>'));}
function documentsPanel(){return card('Attached documents','<p class="note">PDF, PNG, and JPEG files up to 5 MB each. Downloads are restricted to signed-in members of this family.</p>'+(!currentUser?'<p>Sign in through the local server to attach and download files.</p>':documentRows.filter(d=>d.profile===profile().id).map(d=>`<div class="entry"><span class="entry-icon">▤</span><div class="entry-body"><strong>${esc(d.name)}</strong><p>${esc(d.doctor)} · ${esc(d.date)} · ${Math.ceil(d.size/1024)} KB<br>Added by ${esc(d.author)}${d.archived?' · Archived':''}</p></div><a class="text-button" href="/api/document/${encodeURIComponent(d.id)}" download>Download</a><button class="text-button" data-archive-doc="${esc(d.id)}" data-archived="${d.archived?'0':'1'}">${d.archived?'Restore':'Archive'}</button></div>`).join('')),`<button class="primary" data-upload-document ${!currentUser?'disabled':''}>Attach document</button>`);}
function stockPanel(){return card('Medication stock & corrections',profile().medications.map(m=>{const stock=Care.stock(profile(),m);return `<div class="entry"><div class="entry-body"><strong>${esc(m.name)}</strong><p>${stock===null?'Stock tracking not configured':stock+' units remaining'+(stock<=(m.lowStockAt??5)?' · Low stock':'')}<br>${(m.weekdays||[0,1,2,3,4,5,6]).map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')}</p></div><button class="secondary" data-med-settings="${esc(m.id)}">Days & stock</button><button class="text-button" data-restock="${esc(m.id)}">Add stock</button></div>`;}).join('')+'<h2>Correct an administration</h2><p class="note">The original record remains in the history. Every correction needs a reason.</p>'+[...profile().doses].reverse().slice(0,30).map(d=>`<div class="entry"><div class="entry-body"><strong>${esc(d.name)} · ${esc(d.status)}</strong><p>${esc(fmt(d.scheduled))} · ${(d.corrections||[]).length} corrections</p></div><button class="text-button" data-correct-dose="${esc(d.id)}">Correct</button></div>`).join(''));}
render=function(){
  Care.upgrade(familyData);
  const custom={shifts:['Caregiver Shifts',shiftScreen],consultation:['Prepare a Visit',consultationScreen],history:['History & Recovery',historyScreen],settings:['Settings & Security',settingsScreen]};
  if(custom[view]){nav();$('#pageTitle').textContent=custom[view][0];$('#breadcrumb').textContent=custom[view][0];$('#pageSubtitle').textContent='Care for '+profile().name;$('#content').innerHTML=custom[view][1]();}else originalEnhancedRender();
  if(view==='documents')$('#content').insertAdjacentHTML('afterbegin',documentsPanel());
  if(view==='settings'&&currentUser)$('#content').insertAdjacentHTML('beforeend',card('Automatic backup status',`<p>${systemInfo?.lastBackup?'Last encrypted server backup: '+esc(fmt(systemInfo.lastBackup)):'Waiting for the first encrypted server backup.'}</p><p class="note">${esc(systemInfo?.backupError||'The server creates an encrypted full backup daily while running and retains the last 14. Family restore points are also saved before each change.')}</p>${systemInfo?.pushError?'<p class="note">'+esc(systemInfo.pushError)+'</p>':''}`));
  if(view==='medication'){$('#content').insertAdjacentHTML('beforeend',stockPanel());$('#content').querySelectorAll('.entry p').forEach(p=>{if(p.textContent.includes(' daily · '))p.textContent=p.textContent.replace(' daily · ',' · See selected days below · ');});}
  if(view==='family'&&currentUser?.role==='owner')$('#content').insertAdjacentHTML('beforeend',card('Member permissions',members.filter(m=>m.id!==currentUser.id).map(m=>`<div class="entry"><div class="entry-body"><strong>${esc(m.name)}</strong><p>${esc(m.role)}</p></div><button class="secondary" data-role-member="${esc(m.id)}">Change access</button></div>`).join('')+'<button class="secondary" data-viewer-invite>Create view-only invitation</button>'));
  $('#importButton').disabled=!editingAllowed();
  if(!editingAllowed()){$('#addButton').disabled=true;$('#content').querySelectorAll('button').forEach(b=>{if([...b.attributes].some(a=>/^data-(new-|edit|delete|dose|stop-|task-|accept-|correct|restock|med-settings|upload|archive|claim|save-zone)/.test(a.name)))b.disabled=true;});}else $('#addButton').disabled=false;
  const zone=profile().timezone;if(zone&&zone!==Intl.DateTimeFormat().resolvedOptions().timeZone)$('#pageSubtitle').textContent+=' · Care time zone: '+zone+' (different from this device)';
};
async function loadPanels(){if(currentUser){if(view==='history'){const [a,b]=await Promise.all([api('audit'),api('backups')]);historyRows=a.records;backupRows=b.backups;}if(view==='documents')documentRows=(await api('documents')).documents;if(view==='settings'){[securityInfo,systemInfo]=await Promise.all([api('security'),api('system-status')]);}}else if(view==='history')historyRows=JSON.parse(localStorage.getItem('kindred-local-history')||'[]').reverse();render();}
function shiftDialog(existing){openWorkflow(existing?'Edit shift':'Add caregiver shift',field('Responsible caregiver','caregiver','text',existing?.caregiver||actor(),'required maxlength="80"')+field('Backup caregiver','backup','text',existing?.backup||'','maxlength="80"')+field('Start','start','datetime-local',existing?.start||localDate(),'required')+field('End','end','datetime-local',existing?.end||'','required')+area('Handoff / responsibilities','notes',existing?.notes||'','maxlength="3000"'),d=>{const start=d.get('start'),end=d.get('end');if(end<=start)throw Error('The shift must end after it starts.');const caregiver=requiredText(d,'caregiver');if(profile().shifts.some(s=>s.id!==existing?.id&&s.caregiver===caregiver&&s.start<end&&s.end>start))throw Error('This caregiver already has an overlapping shift.');const item={id:existing?.id||Care.id(),caregiver,backup:d.get('backup').trim(),start,end,notes:d.get('notes').trim()};if(existing)Object.assign(existing,item);else profile().shifts.push(item);reasonForChange('Care shift scheduled');persist();});}
function questionDialog(existing){openWorkflow(existing?'Edit consultation question':'Question for the doctor',field('Question','title','text',existing?.title||'','required maxlength="200"')+field('Doctor','doctor','text',existing?.doctor||'','maxlength="100"')+field('Visit date','date','date',existing?.date||'')+area('Answer / notes','answer',existing?.answer||'','maxlength="4000"')+`<label>Status<select name="status"><option value="open">To discuss</option><option value="answered" ${existing?.status==='answered'?'selected':''}>Answered</option></select></label>`,d=>{const item={id:existing?.id||Care.id(),title:requiredText(d,'title'),doctor:d.get('doctor').trim(),date:d.get('date'),answer:d.get('answer').trim(),status:d.get('status'),author:actor()||'Local caregiver'};if(existing)Object.assign(existing,item);else profile().questions.push(item);persist();});}
const existingReport=report;
report=function(){existingReport();if($('#reportEntries')?.querySelector('.report-summary'))$('#reportEntries').insertAdjacentHTML('beforeend','<h2>Questions for the consultation</h2>'+questionsMarkup());};
const oldOpenWorkflow=openWorkflow;
openWorkflow=function(...args){oldOpenWorkflow(...args);addDictation($('#workflowDialog'));};
function addDictation(container){if(!(window.SpeechRecognition||window.webkitSpeechRecognition))return;for(const textarea of container.querySelectorAll('textarea')){if(textarea.nextElementSibling?.hasAttribute('data-dictate'))continue;const b=document.createElement('button');b.type='button';b.className='text-button';b.dataset.dictate=textarea.name;b.textContent='🎙 Dictate';textarea.after(b);}}
$('#entryDialog').addEventListener('toggle',()=>{if($('#entryDialog').open)addDictation($('#entryDialog'));});
let recognition;
document.addEventListener('click',async event=>{
  const b=event.target.closest('button');if(!b)return;
  try{
    if(b.dataset.view&&['history','settings','documents'].includes(b.dataset.view))await loadPanels();
    if(b.hasAttribute('data-new-shift'))shiftDialog();if(b.dataset.editShift)shiftDialog(profile().shifts.find(s=>s.id===b.dataset.editShift));
    if(b.dataset.deleteShift&&confirm('Remove this shift? It will remain in the change history.')){reasonForChange('Shift removed');profile().shifts=profile().shifts.filter(s=>s.id!==b.dataset.deleteShift);persist();render();}
    if(b.dataset.claimTask){if(!actor())throw Error('Set your caregiver name in Family & Accounts first.');profile().tasks.find(t=>t.id===b.dataset.claimTask).assignee=actor();persist();render();}
    if(b.hasAttribute('data-new-question'))questionDialog();if(b.dataset.editQuestion)questionDialog(profile().questions.find(q=>q.id===b.dataset.editQuestion));
    if(b.dataset.medSettings){const m=profile().medications.find(m=>m.id===b.dataset.medSettings);openWorkflow('Medication days & stock',`<fieldset><legend>Prescribed days</legend><div class="weekday-options">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=>`<label class="checkbox"><input type="checkbox" name="days" value="${i}" ${(m.weekdays||[0,1,2,3,4,5,6]).includes(i)?'checked':''}>${d}</label>`).join('')}</div></fieldset>`+field('Starting stock (leave empty to disable tracking)','stock','number',m.stockInitial??'','min="0" step="0.01"')+field('Stock units used per administration','units','number',m.unitsPerDose||1,'min="0.01" step="0.01" required')+field('Low-stock threshold','low','number',m.lowStockAt??5,'min="0" step="0.01"')+`<label>Caregiver for unrecorded-dose alerts<select name="responsible"><option value="">Not assigned</option>${members.map(x=>`<option value="${esc(x.id)}" ${m.responsibleId===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`+field('Reason for change','reason','text','','required maxlength="500"'),d=>{const days=d.getAll('days').map(Number);if(!days.length)throw Error('Select at least one prescribed day.');m.weekdays=days;m.stockInitial=d.get('stock')===''?null:Number(d.get('stock'));m.unitsPerDose=Number(d.get('units'));m.lowStockAt=Number(d.get('low'));m.responsibleId=d.get('responsible');reasonForChange(requiredText(d,'reason'));persist();});}
    if(b.dataset.restock){const m=profile().medications.find(m=>m.id===b.dataset.restock);if(m.stockInitial==null)throw Error('Set the starting stock first.');openWorkflow('Add medication stock',field('Units added','quantity','number','','required min="0.01" step="0.01"')+field('Note','note','text','','maxlength="300"'),d=>{m.restocks.push({id:Care.id(),quantity:Number(d.get('quantity')),note:d.get('note').trim(),author:actor()||'Local caregiver',at:new Date().toISOString()});reasonForChange('Medication restocked');persist();});}
    if(b.dataset.correctDose){const dose=profile().doses.find(d=>d.id===b.dataset.correctDose);openWorkflow('Correct administration',`<p>${esc(dose.name)} · ${esc(fmt(dose.scheduled))}</p><label>Correct status<select name="status"><option value="taken">Taken</option><option value="skipped">Skipped</option></select></label>`+area('Correct administration note / skip reason','note',dose.reason)+field('Why is this correction needed?','reason','text','','required maxlength="500"'),d=>{const status=d.get('status'),note=d.get('note').trim(),reason=requiredText(d,'reason');if(status==='skipped'&&!note)throw Error('A skipped administration needs a reason.');dose.corrections??=[];dose.corrections.push({id:Care.id(),before:{status:dose.status,reason:dose.reason},after:{status,reason:note},reason,author:actor()||'Local caregiver',at:new Date().toISOString()});dose.status=status;dose.reason=note;reasonForChange(reason);persist();});}
    if(b.hasAttribute('data-refresh-history'))await loadPanels();
    if(b.dataset.restoreRecord||b.dataset.restoreBackup){if(syncDirty||syncBusy)throw Error('Sync your current changes before restoring.');const isBackup=!!b.dataset.restoreBackup;openWorkflow(isBackup?'Restore family snapshot':'Restore deleted record',field('Reason for restoring','reason','text','','required maxlength="500"'),async d=>{if(currentUser){await api(isBackup?'restore-backup':'restore-record',{id:b.dataset.restoreBackup||b.dataset.restoreRecord,revision:serverRevision,reason:requiredText(d,'reason')});await refreshFamily();await loadPanels();}else{const row=historyRows.find(r=>r.id===b.dataset.restoreRecord),p=familyData.profiles.find(p=>p.id===row.profile);if(!p)throw Error('Parent profile no longer exists.');if(p[row.collection].some(r=>r.id===row.before.id))throw Error('This record already exists.');p[row.collection].push(row.before);reasonForChange(requiredText(d,'reason'));persist();historyRows=JSON.parse(localStorage.getItem('kindred-local-history')||'[]').reverse();}},'Restore');}
    if(b.hasAttribute('data-review-merge')){const review=mergeReview;openWorkflow('Resolve conflicting changes',review.conflicts.map((c,i)=>`<fieldset><legend>${esc(c.path.split('/').slice(-2).join(' / '))}</legend><p class="note">Mine: ${esc(JSON.stringify(c.local)??'Deleted')}<br>Shared: ${esc(JSON.stringify(c.remote)??'Deleted')}</p><label>Keep<select name="choice${i}"><option value="remote">Shared version</option><option value="local">My version</option></select></label></fieldset>`).join(''),d=>{const choices=Object.fromEntries(review.conflicts.map((c,i)=>[c.path,d.get('choice'+i)]));const merged=Care.merge(review.base,review.local,review.remote,choices);Care.validate(merged.state);familyData=merged.state;syncBase=review.remote;serverRevision=review.revision;syncConflict=false;syncDirty=true;mergeReview=null;$('#syncConflict')?.remove();saveCache();void pushChanges();},'Save resolved changes');}
    if(b.hasAttribute('data-upload-document')){if(syncDirty)throw Error('Sync the profile before attaching a document.');openWorkflow('Attach a care document','<label>PDF, PNG or JPEG (up to 5 MB)<input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required></label>'+field('Doctor / clinic','doctor','text','','maxlength="200"')+field('Document date','date','date',Care.day()),async d=>{const file=d.get('file');if(file.size>5*1024*1024)throw Error('Maximum file size is 5 MB.');const buffer=new Uint8Array(await file.arrayBuffer());let raw='';for(let i=0;i<buffer.length;i+=8192)raw+=String.fromCharCode(...buffer.subarray(i,i+8192));await api('upload-document',{profile:profile().id,name:file.name,doctor:d.get('doctor'),date:d.get('date'),body:btoa(raw)});documentRows=(await api('documents')).documents;},'Upload document');}
    if(b.dataset.archiveDoc){await api('archive-document',{id:b.dataset.archiveDoc,archived:b.dataset.archived==='1'});await loadPanels();}
    if(b.dataset.roleMember)openWorkflow('Change member access','<label>Permission<select name="role"><option value="caregiver">Caregiver — view and edit care</option><option value="viewer">View only — read records and documents</option></select></label>',async d=>{await api('member-role',{id:b.dataset.roleMember,role:d.get('role')});members=(await api('members')).members;});
    if(b.hasAttribute('data-viewer-invite')){const r=await api('invite',{role:'viewer'});openWorkflow('View-only invitation',`<p>One use · expires in ${esc(r.expiresIn)}.</p>${field('Share this code privately','invite','text',r.token,'readonly')}`,()=>{},'Done');}
    if(b.hasAttribute('data-save-zone')){const zone=$('#careTimezone').value.trim();try{new Intl.DateTimeFormat('en',{timeZone:zone});}catch{throw Error('Enter a time zone such as Europe/Bucharest.');}profile().timezone=zone;persist();toast('Care time zone saved.');}
    if(b.hasAttribute('data-install-app')){if(installPrompt){await installPrompt.prompt();installPrompt=null;}else openWorkflow('Install Kindred','<p>Use your browser’s Install app or Add to Home Screen command when available. The server address is local to this computer. Offline access becomes available after the app has loaded successfully.</p>',()=>{},'Done');}
    if(b.dataset.dictate){const target=b.previousElementSibling,Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(recognition){recognition.stop();recognition=null;return;}recognition=new Speech();recognition.lang='en-US';recognition.onresult=e=>{target.value+=(target.value?' ':'')+e.results[0][0].transcript;target.dispatchEvent(new Event('input',{bubbles:true}));};recognition.onerror=()=>toast('Dictation is unavailable or microphone access was declined.');recognition.onend=()=>{b.textContent='🎙 Dictate';recognition=null;};recognition.start();b.textContent='Stop dictation';}
    if(b.hasAttribute('data-enable-push')){if(!('serviceWorker'in navigator)||!('PushManager'in window))throw Error('This browser does not support background push. Use calendar export.');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Notification permission was not granted.');const config=await api('push-config');if(!config.available)throw Error('Push dependencies are not installed on the server.');const registration=await navigator.serviceWorker.ready;const bytes=Uint8Array.from(atob(config.publicKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const sub=await registration.pushManager.getSubscription()||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await api('push-subscribe',{subscription:sub.toJSON(),timezone:profile().timezone,escalate:$('#escalatePush').checked});toast('Background reminders enabled for this browser.');}
    if(b.hasAttribute('data-disable-push')){await api('push-disable',{});const reg=await navigator.serviceWorker?.getRegistration();const sub=await reg?.pushManager.getSubscription();await sub?.unsubscribe();toast('Background reminders disabled.');}
    if(b.hasAttribute('data-twofactor'))securityDialog(securityInfo?.enabled?'disable':'setup');
    if(b.hasAttribute('data-recovery-codes'))securityDialog('recovery');
    if(b.hasAttribute('data-change-password'))securityDialog('password');
    if(b.hasAttribute('data-reset-password'))resetDialog();
  }catch(error){toast(error.message);}
});
function securityDialog(action){let result;openWorkflow('Verify account security',field('Current password','password','password','','required autocomplete="current-password"')+(securityInfo?.enabled?field('Authenticator code','otp','text','','required inputmode="numeric" pattern="[0-9]{6}"'):'')+(action==='password'?field('New password','newPassword','password','','required minlength="12" maxlength="256" autocomplete="new-password"'):''),async d=>{result=await api('security/'+action,Object.fromEntries(d));setTimeout(()=>{if(action==='setup'){openWorkflow('Connect your authenticator',field('Manual setup key','secret','text',result.secret,'readonly')+'<p class="note">Add this key in your authenticator app as a time-based code. Confirm the code below to activate two-step sign-in.</p>'+field('Current password','password','password','','required')+field('Six-digit authenticator code','otp','text','','required inputmode="numeric" pattern="[0-9]{6}"'),async form=>{await api('security/enable',Object.fromEntries(form));securityInfo=await api('security');},'Enable two-step sign-in');}else if(action==='recovery'){openWorkflow('Save your recovery codes',`<p>Each code can be used once. These codes will not be shown again.</p><pre class="recovery-codes">${esc(result.codes.join('\n'))}</pre><button type="button" class="secondary" id="downloadRecovery">Download codes</button>`,()=>{},'I have saved my codes');$('#downloadRecovery').onclick=()=>download('kindred-recovery-codes.txt',result.codes.join('\n'),'text/plain');}else{void loadPanels();toast('Account security updated.');}},0);});}
function resetDialog(){openWorkflow('Recover your account',field('Email','email','email','','required autocomplete="email"')+field('Unused recovery code','recovery','text','','required')+field('New password','password','password','','required minlength="12" maxlength="256" autocomplete="new-password"')+'<p class="note">This signs out existing sessions and resets two-step sign-in. Set up your authenticator again after signing in.</p>',async d=>{await api('reset-password',Object.fromEntries(d));toast('Password reset. Sign in with the new password.');},'Reset password');}
// Enforce view-only controls before legacy click listeners mutate state.
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(!editingAllowed()&&(b.id==='addButton'||b.id==='profileButton'||[...b.attributes].some(a=>/^data-(add|new-|edit|delete|dose|done|stop-|task-|accept-|correct|restock|med-settings|upload|archive|claim|save-zone)/.test(a.name)))){event.preventDefault();event.stopImmediatePropagation();toast(profile().isDemo?'Demo examples are read-only. Switch back to your care profile to add records.':'Your account has view-only access.');}if(b.dataset.delete&&editingAllowed()){event.preventDefault();event.stopImmediatePropagation();const id=b.dataset.delete;openWorkflow('Delete journal entry',field('Reason for deletion','reason','text','','required maxlength="500"'),d=>{reasonForChange(requiredText(d,'reason'));profile().entries=profile().entries.filter(e=>e.id!==id);persist();},'Delete entry');}},true);
document.addEventListener('change',event=>{if(['textScale','highContrast'].includes(event.target.id)){localStorage.setItem('kindred-accessibility',JSON.stringify({scale:$('#textScale').value,contrast:$('#highContrast').checked}));applyAccessibility();}});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;});
window.addEventListener('online',()=>{if(currentUser)api('me').then(attachAccount).catch(()=>syncStatus('Reconnect to sync your saved changes'));});
window.addEventListener('offline',()=>syncStatus('Offline · changes stay on this device'));
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>toast('Offline installation is unavailable in this browser.'));
function restoreOfflineSession(){if(currentUser)return;try{const last=JSON.parse(localStorage.getItem('kindred-last-account'));const cache=last&&JSON.parse(localStorage.getItem('kindred-account-'+last.id));if(cache){Care.validate(cache.state);familyData=Care.upgrade(cache.state);currentUser={...last,csrf:''};serverRevision=cache.revision;syncDirty=cache.pending;syncBase=cache.base||structuredClone(familyData);activeProfileId=familyData.profiles[0].id;render();syncStatus('Offline · changes stay on this device');}}catch{}}
if(!navigator.onLine)restoreOfflineSession();
else if(location.protocol!=='file:')api('health').catch(restoreOfflineSession);
render();
