/* Fictional starter examples. No real people, prescriptions or appointments. */
(function(root){
  const people=['Alex Brooks','Jamie Brooks','Morgan Reed','Casey Lee','Taylor Green','Jordan Ellis','Robin Lane','Sam Parker','Drew Miller','Avery Quinn'];
  const samples={
    medication:[['Morning medication note','The sample medication checklist was reviewed. Administration is recorded separately.'],['Evening medication note','The evening care notes were prepared for the next caregiver.'],['Prescription list updated','A fictional prescription list was added to the care folder.'],['Medication organizer checked','The demo organizer was checked against the fictional medication list.'],['Refill reminder added','A sample prescription renewal reminder was placed on the calendar.'],['Pharmacy collection noted','A fictional collection receipt was recorded for the family.'],['Instructions filed','The example prescription instructions were filed for reference.'],['Medication question for the doctor','A question about the sample medication list was saved for the next visit.'],['Stock count reviewed','The sample stock count was checked for this demonstration.'],['Handoff medication summary','The next caregiver was given a summary of the example administration log.']],
    appointments:[['Primary care review','Bring the fictional care summary and questions list.'],['Vision appointment','Sample appointment at Example Eye Clinic.'],['Dental checkup','Sample appointment at Example Dental Practice.'],['Physiotherapy visit','Example mobility review; no treatment advice is included.'],['Hearing assessment','Bring the fictional appointment letter.'],['Nurse check-in','Review the sample daily care journal.'],['Care planning meeting','Discuss the example weekly care rota with the fictional family.'],['Routine follow-up','Review the example questions prepared for the clinician.'],['Document collection','Collect a sample copy of visit paperwork.'],['Telephone consultation','Fictional call to review the care diary.']],
    vitals:[['Morning readings','Sample readings recorded before breakfast.'],['Afternoon readings','Fictional measurements entered during the afternoon check-in.'],['Evening readings','Sample readings added to the care diary.'],['Weekly measurements','Fictional measurements for demonstrating the trend charts.'],['Pre-visit readings','Example readings included in the consultation report.'],['Daily vital signs','Sample measurements recorded by the visiting caregiver.'],['Quiet-time readings','Fictional measurements entered while resting.'],['Care review readings','Example measurements for a family handoff.'],['Weekend readings','Sample values for the weekend care journal.'],['Latest measurements','Fictional readings showing how the report displays recent values.']],
    symptoms:[['Appetite observation','Reported less interest in lunch in this fictional example.'],['Energy observation','Reported feeling tired after the morning activities.'],['Joint comfort note','Mentioned stiffness while getting ready for the day.'],['Dry mouth note','Mentioned dry mouth during the afternoon check-in.'],['Headache observation','A fictional headache note was added with its time.'],['Digestion note','Reported mild stomach discomfort after a meal.'],['Skin comfort observation','Mentioned an itchy patch; the note was saved for discussion.'],['Cough observation','A sample note records when a cough was noticed.'],['Dizziness observation','A fictional episode was recorded with context for the care diary.'],['Symptom follow-up','The next caregiver was asked to review the existing sample notes.']],
    meals:[['Breakfast and water','Oatmeal, fruit, and a glass of water were logged.'],['Morning snack','Yogurt and tea were recorded in this sample.'],['Lunch','Vegetable soup and toast were logged.'],['Afternoon water','A glass of water was recorded during the afternoon visit.'],['Dinner','Rice, vegetables, and a small serving of chicken were logged.'],['Evening drink','A cup of herbal tea was recorded.'],['Breakfast appetite','About half of the sample breakfast was eaten.'],['Lunch with family','A sandwich and fruit were logged during a family visit.'],['Snack and drink','Crackers and a glass of water were recorded.'],['Daily food summary','The fictional meal diary was summarized for the next caregiver.']],
    daily:[['Morning wash','Help with the morning routine was recorded.'],['Getting dressed','Clothes were prepared and assistance was logged.'],['Room tidied','The room was tidied and frequently used items placed nearby.'],['Laundry completed','Clean clothes and towels were put away.'],['Bedding changed','Fresh bedding was recorded in the care journal.'],['Short walk','A fictional accompanied walk was logged.'],['Personal items organized','Glasses and personal items were placed in their usual spots.'],['Evening routine','The sample evening routine was completed.'],['Household supplies checked','The family shopping list was updated.'],['Daily care handoff','Completed activities were summarized for the next caregiver.']],
    mood:[['Calm morning','Appeared relaxed during the fictional morning visit.'],['Enjoyed music','Smiled and engaged while listening to familiar songs.'],['Quiet afternoon','Preferred a quiet afternoon with fewer activities.'],['Family visit','Enjoyed a short fictional visit from relatives.'],['Worried before appointment','Expressed concern about an upcoming example appointment.'],['Interested in photos','Looked through a family photo album with the caregiver.'],['Conversation note','Participated in a longer conversation during the visit.'],['Restless evening','A fictional change in evening behavior was noted.'],['Good engagement','Enjoyed choosing an activity for the afternoon.'],['Mood summary','The day’s fictional observations were summarized without a diagnosis.']],
    sleep:[['Overnight sleep','Sample sleep interval: 22:30 to 06:30.'],['Afternoon nap','A fictional 35-minute afternoon nap was recorded.'],['Interrupted night','Two awakenings were noted in this example.'],['Bedtime routine','The evening routine was logged at 21:45.'],['Morning wake-up','Awoke at 07:00 in the sample diary.'],['Rest period','A quiet rest period was recorded after lunch.'],['Nighttime note','A fictional overnight caregiver check was logged.'],['Earlier bedtime','Went to bed at 21:30 in this sample.'],['Sleep diary review','The fictional weekly sleep diary was reviewed.'],['Latest sleep entry','Sample sleep interval: 22:00 to 06:45.']],
    incidents:[['Near-trip noted','A fictional near-trip by a rug was documented.'],['Spilled drink','A drink spilled near the chair; cleanup was recorded.'],['Misplaced glasses','Glasses were temporarily misplaced and later found.'],['Doorway obstruction','An item left in a doorway was noted and moved.'],['Chair transfer incident','A fictional loss of balance during a transfer was documented.'],['Bathroom near-slip','A fictional near-slip was recorded for the care team.'],['Dropped item','A dropped cup and cleanup were logged.'],['Outdoor stumble','A fictional stumble during an accompanied walk was documented.'],['Fall record example','This fictional record demonstrates where incident details and follow-up notes go.'],['Incident follow-up','The sample incident notes were reviewed at the next handoff.']],
    doctor:[['Visit preparation','Bring the fictional medication list and recent care summary.'],['Questions recorded','The family’s example questions were listed before the visit.'],['Visit summary filed','A fictional consultation summary was added to the documents register.'],['Follow-up date noted','The sample follow-up date was entered in the calendar.'],['Measurements shared','Example readings were included in the visit report.'],['Prescription paperwork','A fictional prescription document was indexed for reference.'],['Care routine discussion','A sample note records a discussion about the daily routine.'],['Contact details checked','The fictional clinic contact label was reviewed.'],['Consultation answer logged','An example answer was recorded in Prepare a Visit.'],['After-visit handoff','The fictional visit notes were summarized for the next caregiver.']],
    expenses:[['Groceries','Fictional receipt for household groceries.'],['Transport to appointment','Sample transport expense, not a current service price.'],['Personal care supplies','Fictional purchase recorded for family budgeting.'],['Laundry supplies','Sample household expense.'],['Meal delivery','Fictional meal expense for demonstrating the expense log.'],['Parking','Sample parking receipt associated with an appointment.'],['Cleaning supplies','Fictional household purchase.'],['Document printing','Sample printing expense.'],['Replacement household item','Fictional purchase of a household item.'],['Weekly care supplies','Sample expense summary for the family.']],
    team:[['Alex Brooks · Family coordinator','Fictional contact. Coordinates the sample weekly rota.'],['Jamie Brooks · Morning caregiver','Fictional contact. Covers the sample morning routine.'],['Morgan Reed · Evening caregiver','Fictional contact. Reviews the sample evening handoff.'],['Casey Lee · Backup caregiver','Fictional contact. Available for example backup shifts.'],['Taylor Green · Appointment companion','Fictional contact. Accompanies sample appointments.'],['Jordan Ellis · Shopping support','Fictional contact. Helps with the example shopping list.'],['Robin Lane · Household support','Fictional contact. Helps with sample household tasks.'],['Sam Parker · Weekend caregiver','Fictional contact. Covers the example weekend rota.'],['Drew Miller · Document organizer','Fictional contact. Maintains the sample documents register.'],['Avery Quinn · Family check-in','Fictional contact. Reviews the sample weekly summary.']],
    documents:[['Care summary.pdf','Demo register entry only; no file is attached.'],['Medication list.pdf','Demo register entry only; fictional medication list.'],['Visit notes.pdf','Demo register entry only; fictional consultation notes.'],['Appointment letter.pdf','Demo register entry only; fictional appointment letter.'],['Emergency information.pdf','Demo register entry only; fictional contact sheet.'],['Care rota.pdf','Demo register entry only; fictional caregiver schedule.'],['Receipt archive.pdf','Demo register entry only; fictional expense receipts.'],['Measurement summary.pdf','Demo register entry only; fictional readings.'],['Questions for the doctor.pdf','Demo register entry only; fictional visit questions.'],['Weekly handoff.pdf','Demo register entry only; fictional weekly summary.']]
  };
  function create(now=new Date()){
    const C=root.Care,today=C.day(now),p=C.freshProfile('Demo · Eleanor Brooks');p.id='kindred-demo-profile';p.isDemo=true;p.allergies='Fictional profile. No real allergy information is recorded.';
    p.emergency=people.map((name,i)=>`${i+1}. ${name} — fictional care contact; no real phone number.`).join('\n');
    p.timezone=Intl.DateTimeFormat().resolvedOptions().timeZone;p.shifts=[];p.questions=[];
    const reading=[128,132,126,134,130,129,136,131,127,130];
    for(const [category,rows] of Object.entries(samples))rows.forEach(([title,notes],i)=>{
      const future=category==='appointments'&&i>=5;
      const date=C.addDays(today,future?i-4:i-9)+'T'+(category==='appointments'?'10:00':category==='sleep'?'07:30':'09:00');
      const e={id:`demo-${category}-${i+1}`,category,title,date,author:people[i],notes,done:category==='appointments'&&!future,handoff:i===9,amount:category==='expenses'?[42.50,18,24.75,12.90,16,5,14.50,3.25,22,38][i]:null,unit:category==='expenses'?'USD':''};
      if(category==='vitals')e.vitals={systolic:reading[i],diastolic:[78,80,76,82,79,78,83,80,77,79][i],pulse:68+i%5,temperature:36.5+(i%3)/10,oxygen:97+i%2,weight:68.5+(i%4)/10};
      p.entries.push(e);
    });
    for(let i=0;i<10;i++){
      const n=i+1,day=C.addDays(today,i-9),time=i%2?'20:00':'08:00',scheduled=day+'T'+time;
      const m={id:'demo-plan-'+n,name:'Example medication '+String.fromCharCode(65+i),dosage:'Fictional prescribed dose',instructions:'Demonstration only. This is not a real prescription.',times:[time],start:C.addDays(today,-15),end:'',active:true,weekdays:[0,1,2,3,4,5,6],stockInitial:20+i*3,unitsPerDose:1,lowStockAt:5,restocks:[],responsibleId:''};p.medications.push(m);
      // All administration examples are historical, even when opened just after midnight.
      const doseScheduled=C.addDays(today,i-10)+'T'+time;
      p.doses.push({id:'demo-dose-'+n,medicationId:m.id,scheduled:doseScheduled,status:i===3||i===7?'skipped':'taken',author:people[i],reason:i===3||i===7?'Fictional omission recorded for the demonstration.':'',recordedAt:new Date(doseScheduled).toISOString(),name:m.name,dosage:m.dosage});
      p.tasks.push({id:'demo-task-'+n,title:['Prepare breakfast','Check household supplies','Update care journal','Prepare appointment folder','Renew example prescription','Arrange laundry','Prepare evening meal','Review medication stock','Check next caregiver handoff','Review weekly care plan'][i],date:C.addDays(today,i<5?0:i-4)+'T'+['08:00','09:00','10:00','11:00','12:00','13:00','14:00','16:00','18:00','20:00'][i],assignee:people[i],notes:'Fictional task for exploring the calendar.',kind:i===4?'refill':'care',repeat:i<3?'daily':'none',completed:[],active:true});
      p.shifts.push({id:'demo-shift-'+n,caregiver:people[i],backup:people[(i+1)%10],start:C.addDays(today,i-4)+'T08:00',end:C.addDays(today,i-4)+'T18:00',notes:'Fictional care shift. Review the demo handoff and daily task list.'});
      p.questions.push({id:'demo-question-'+n,title:['What information should we bring to the next visit?','Which changes should we record in the diary?','Can we review the medication list together?','What should the family include in the care summary?','When should the next routine visit be scheduled?','Which documents should we keep available?','Can we discuss the recent sleep diary?','What questions should the next caregiver bring?','Can we review the sample measurement log?','How should we prepare for the follow-up appointment?'][i],doctor:'Example Clinic',date:C.addDays(today,i+1),answer:i<4?'Fictional answer placeholder — record the clinician’s actual response here.':'',status:i<4?'answered':'open',author:people[i]});
      const h={id:'demo-handoff-'+n,from:people[i],to:people[(i+1)%10],toId:'',createdAt:new Date(C.addDays(today,i-10)+'T18:00').toISOString(),summary:`DEMO ONLY · Fictional handoff ${n}\nDaily care and meal notes reviewed.\nSee the example medication log and upcoming care tasks.`,notes:'Fictional handoff. No real caregiver is being notified.',status:i<7?'accepted':'pending'};
      if(i<7){h.acceptedBy=h.to;h.acceptedAt=new Date(C.addDays(today,i-10)+'T18:15').toISOString();}p.handoffs.push(h);
    }
    // Exactly 20 records across the whole demo: 13 journal entries + 7 workflow records.
    p.entries=Object.keys(samples).map(category=>p.entries.filter(e=>e.category===category).at(category==='appointments'?-2:-1));
    p.medications=p.medications.slice(0,2);
    p.doses=p.doses.slice(0,1);
    p.tasks=p.tasks.slice(0,1);
    p.shifts=[p.shifts[4]];
    p.questions=[p.questions[4]];
    p.handoffs=[p.handoffs[9]];
    p.emergency='Fictional emergency contact: Alex Brooks. Demonstration only; no real phone number is included.';
    C.validate({version:2,profiles:[p]});return p;
  }
  root.KindredExamples={create,id:'kindred-demo-profile',categories:Object.keys(samples)};
})(globalThis);
