/* Extended family workflows, backed by the optional same-origin family server. */
let familyData, activeProfileId, currentUser=null, serverRevision=0, syncBusy=false, syncDirty=false, syncConflict=false, serverAvailable=false, members=[];
const LOCAL_KEY='kindred-family-v2';
try { const saved=localStorage.getItem(LOCAL_KEY); familyData=saved?Care.migrate(JSON.parse(saved)):Care.migrate(state); }
catch { familyData={version:2,profiles:[Care.freshProfile()]}; toast('Could not load the family backup. Your previous storage has not been overwritten.'); }
activeProfileId=localStorage.getItem('kindred-active-local')||familyData.profiles[0].id;
function profile(){return familyData.profiles.find(p=>p.id===activeProfileId)||familyData.profiles[0];}
state={get profile(){return profile();},get entries(){return profile().entries;},set entries(entries){profile().entries=entries;}};
const oldRender=render,oldNav=nav,oldExtras=extras,oldOpenEntry=openEntry,oldHandoffText=handoffText;
const chosenDay={medication:Care.day(),calendar:Care.day()};
function actor(){return currentUser?.name||localStorage.getItem('kindred-caregiver')||'';}
function cacheKey(){return currentUser?'kindred-account-'+currentUser.id:LOCAL_KEY;}
let lastSaveError='';
function saveCache(){
  lastSaveError='';
  try{localStorage.setItem(cacheKey(),JSON.stringify(currentUser?{state:familyData,revision:serverRevision,pending:syncDirty}:familyData));return true;}
  catch(error){lastSaveError=['QuotaExceededError','NS_ERROR_DOM_QUOTA_REACHED'].includes(error.name)?'The browser storage limit is still full after lossless compaction. Download a backup before freeing browser storage.':error.name==='SecurityError'?'This browser is blocking local storage. Allow site data for Kindred and try again.':'Could not write care data to this browser: '+error.message;toast(lastSaveError);return false;}
}
persist=function(){lastSaveError='';try{Care.validate(familyData);}catch(e){lastSaveError=e.message;toast(e.message);return false;}syncDirty=!!currentUser;const saved=saveCache();syncStatus();if(currentUser)void pushChanges();return saved;};
function syncStatus(message){const el=$('#syncStatus');if(el)el.textContent=message||(syncConflict?'Sync conflict · review required':currentUser?(syncDirty?'Changes waiting to sync':'Connected · '+currentUser.name):'Saved on this device');}
async function api(path,body){
  const response=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':currentUser?.csrf||''}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});
  const result=await response.json();if(!response.ok){const error=new Error(result.error||'Request failed.');error.status=response.status;throw error;}return result;
}
async function pushChanges(){
  if(!currentUser||syncBusy||syncConflict||!syncDirty)return;
  syncBusy=true;
  try{
    while(syncDirty){const snapshot=JSON.stringify(familyData);const result=await api('state',{revision:serverRevision,state:JSON.parse(snapshot)});serverRevision=result.revision;syncDirty=JSON.stringify(familyData)!==snapshot;saveCache();}
    syncStatus();
  }catch(e){if(e.status===409){syncConflict=true;showConflict();}else{syncStatus('Not synced · retrying');toast(e.message+' Your changes remain on this device.');}}
  finally{syncBusy=false;}
}
function showConflict(){syncStatus();if(!$('#syncConflict')){const banner=document.createElement('div');banner.id='syncConflict';banner.className='conflict-banner';banner.innerHTML='<strong>Another caregiver saved changes.</strong><p>Your unsynced version is preserved on this device. Download it before loading the latest family version, then reapply the updates you still need.</p><button class="secondary" data-local-copy>Download my version</button> <button class="primary" data-load-latest>Load latest family version</button>';$('.page').prepend(banner);}}
async function attachAccount(user){
  const remote=await api('state');Care.validate(remote.state);const nextMembers=(await api('members')).members;currentUser=user;
  let cache;try{cache=JSON.parse(localStorage.getItem(cacheKey()));}catch{}
  familyData=remote.state;serverRevision=remote.revision;syncDirty=false;syncConflict=false;
  if(cache?.pending){Care.validate(cache.state);familyData=cache.state;serverRevision=cache.revision;syncDirty=true;syncConflict=remote.revision!==cache.revision;}
  activeProfileId=localStorage.getItem('kindred-active-'+currentUser.id)||familyData.profiles[0].id;members=nextMembers;saveCache();render();if(syncConflict)showConflict();else if(syncDirty)void pushChanges();
}
async function refreshFamily(){
  if(!currentUser||syncBusy||syncConflict||document.querySelector('dialog[open]'))return;
  if(syncDirty){void pushChanges();return;}
  try{const remote=await api('state');if(syncDirty||syncBusy||document.querySelector('dialog[open]'))return;if(remote.revision!==serverRevision){Care.validate(remote.state);familyData=remote.state;serverRevision=remote.revision;if(!familyData.profiles.some(p=>p.id===activeProfileId))activeProfileId=familyData.profiles[0].id;saveCache();render();}syncStatus();}catch{syncStatus('Connection interrupted · retrying');}
}
nav=function(){oldNav();$('#navigation').insertAdjacentHTML('afterbegin',navItem(['calendar','Calendar & Reminders','▦']));$('#navigation').insertAdjacentHTML('beforeend',navItem(['family','Family & Accounts','♧']));$('#profilePicker').innerHTML=familyData.profiles.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('#profilePicker').value=profile().id;syncStatus();};
function actions(title,button){return `<div class="card-head"><h2>${title}</h2>${button||''}</div>`;}
function amountText(d){return `${esc(d.name)} · ${esc(d.dosage)}`;}
function doseRows(date){return Care.dosesOn(profile(),date).map(d=>`<div class="entry"><span class="entry-icon">✚</span><div class="entry-body"><div class="entry-title">${esc(d.medication.name)} · ${esc(d.medication.dosage)}</div><p>${esc(d.scheduled.slice(11))} · ${esc(d.medication.instructions)}</p>${d.record?`<span class="badge ${d.record.status==='skipped'?'warning':''}">${d.record.status==='taken'?'Taken':'Skipped'}</span><small> ${esc(d.record.author)} · ${esc(fmt(d.record.recordedAt))}${d.record.reason?' · '+esc(d.record.reason):''}</small>`:`<small>${new Date(d.scheduled)<new Date()?'Not recorded':'Scheduled'}</small>`}</div>${!d.record?`<div class="entry-actions"><button class="secondary" data-dose="${esc(d.medication.id)}" data-at="${esc(d.scheduled)}" ${new Date(d.scheduled)>new Date()?'disabled':''}>Record dose</button></div>`:''}</div>`).join('')||empty('No medication doses scheduled for this date.');}
function medicationScreen(){const p=profile(),next=Care.nextDose(p);return `<section class="welcome"><div><div class="eyebrow">MEDICATION, CLEARLY RECORDED</div><h2>${next?'Next: '+esc(next.medication.name)+' · '+esc(fmt(next.scheduled)):'No upcoming dose scheduled'}</h2><p>Record what was actually given. A journal note does not mark a scheduled dose as taken.</p></div><button class="primary" data-new-medication>＋ Add medication</button></section><section class="card">${actions('Dose schedule','<input type="date" id="doseDate" aria-label="Dose schedule date" value="'+chosenDay.medication+'">')}<div id="doseRows">${doseRows(chosenDay.medication)}</div></section><section class="card">${actions('Medication plans')}<p class="note">Enter the prescribed schedule. To change a plan, stop it and add a new one. Past administration records are retained.</p>${p.medications.map(m=>`<div class="entry"><div class="entry-body"><strong>${esc(m.name)} · ${esc(m.dosage)}</strong><p>${esc(m.times.join(', '))} daily · ${esc(m.start)}${m.end?' to '+esc(m.end):''}</p><p>${esc(m.instructions)}</p><span class="badge">${m.active?'Active':'Stopped'}</span></div>${m.active?`<button class="text-button" data-stop-med="${esc(m.id)}">Stop plan</button>`:''}</div>`).join('')||empty('Add a prescribed medication and its scheduled times.')}</section><section class="card">${actions('Administration history')} ${[...p.doses].sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt)).map(d=>`<div class="entry"><div class="entry-body"><strong>${amountText(d)}</strong><p>${esc(d.status==='taken'?'Taken':'Skipped')} · Scheduled ${esc(fmt(d.scheduled))}<br>Recorded ${esc(fmt(d.recordedAt))} by ${esc(d.author)}${d.reason?'<br>'+esc(d.reason):''}</p></div></div>`).join('')||empty('No administrations recorded.')}</section><section class="card">${actions('Medication notes','<button class="text-button" data-add="medication">Add a note</button>')}${sorted(p.entries.filter(e=>e.category==='medication')).map(entry).join('')||empty('General medication notes appear here.')}</section>`;}
function taskRows(date){return Care.tasksOn(profile(),date).sort((a,b)=>a.occurrence.localeCompare(b.occurrence)).map(t=>`<div class="entry"><span class="entry-icon">${t.kind==='refill'?'✚':'☀'}</span><div class="entry-body"><strong>${esc(t.title)}</strong><p>${esc(t.occurrence.slice(11))} · ${esc(t.assignee||'Unassigned')} · ${esc(t.repeat==='none'?'One time':t.repeat)}<br>${esc(t.notes)}</p>${t.completion?`<small>Completed by ${esc(t.completion.author)} · ${esc(fmt(t.completion.at))}</small>`:''}</div><div class="entry-actions">${!t.completion?`<button class="secondary" data-task-done="${esc(t.id)}" data-day="${date}" ${new Date(t.occurrence)>new Date()?'disabled':''}>Complete</button>`:'<span class="badge">Done</span>'}<button class="text-button" data-task-stop="${esc(t.id)}">${t.repeat==='none'?'Cancel':'Stop repeat'}</button></div></div>`).join('');}
function calendarScreen(){const date=chosenDay.calendar,p=profile();return `<section class="card">${actions('Plan the days ahead','<button class="primary" data-new-task>＋ Add task or reminder</button>')}<div class="toolbar"><label>Selected date<input type="date" id="calendarDate" value="${date}"></label><button class="secondary" data-notifications>Enable browser reminders</button><button class="secondary" data-calendar-export>Export next 30 days</button></div><p class="note">Browser reminders run while this app is open. Export to your calendar for reminders when the app is closed. Times use this device’s local time zone.</p><h2>Care tasks & prescription renewals</h2>${taskRows(date)||empty('No tasks for this date.')}<h2>Appointments</h2>${sorted(p.entries.filter(e=>e.category==='appointments'&&e.date.slice(0,10)===date)).map(entry).join('')||empty('No appointments on this date.')}<h2>Medication</h2>${doseRows(date)}</section><section class="card">${actions('Active reminders')}${p.tasks.filter(t=>t.active).map(t=>`<div class="entry"><div class="entry-body"><strong>${esc(t.title)}</strong><p>Starts ${esc(fmt(t.date))} · ${esc(t.repeat)} · ${esc(t.assignee||'Unassigned')}</p></div><button class="text-button" data-task-stop="${esc(t.id)}">Cancel</button></div>`).join('')||empty('Create a care task, appointment reminder, or prescription renewal.')}</section>`;}
function pendingTasks(){return profile().tasks.filter(t=>t.active&&t.date.slice(0,10)<=Care.day()).flatMap(t=>{const date=t.repeat==='none'?t.date.slice(0,10):Care.day();return Care.tasksOn(profile(),date).filter(o=>o.id===t.id&&!o.completion);});}
handoffText=function(){const p=profile(),next=Care.nextDose(p),today=p.doses.filter(d=>d.scheduled.slice(0,10)===Care.day());return oldHandoffText()+ '\n\nMedication today\n'+(today.map(d=>`${d.name} (${d.dosage}): ${d.status} at ${fmt(d.recordedAt)} by ${d.author}${d.reason?' — '+d.reason:''}`).join('\n')||'No administration recorded.')+'\n\nNext scheduled dose\n'+(next?`${next.medication.name} (${next.medication.dosage}) · ${fmt(next.scheduled)}`:'None scheduled.')+'\n\nRemaining tasks\n'+(pendingTasks().map(t=>`${t.title} · ${fmt(t.occurrence)} · ${t.assignee||'Unassigned'}`).join('\n')||'No outstanding tasks for today.');};
function handoffHistory(){const p=profile(),latest=[...p.handoffs].reverse().find(h=>h.status==='accepted');return `<section class="card">${actions('Caregiver handoff','<button class="primary" data-new-handoff>Prepare handoff</button>')}<p class="note">${latest?'Last confirmed caregiver: '+esc(latest.acceptedBy)+' · '+esc(fmt(latest.acceptedAt)):'No caregiver has confirmed a handoff yet.'}</p>${[...p.handoffs].reverse().map(h=>`<article class="handoff-record"><div class="card-head"><strong>${esc(h.from)} → ${esc(h.to)}</strong><span class="badge">${h.status==='accepted'?'Accepted':'Awaiting acceptance'}</span></div><p class="note">Prepared ${esc(fmt(h.createdAt))}${h.status==='accepted'?'<br>Accepted by '+esc(h.acceptedBy)+' · '+esc(fmt(h.acceptedAt)):''}</p><p>${esc(h.notes)}</p><details><summary>View handoff snapshot</summary><pre>${esc(h.summary)}</pre></details>${h.status==='pending'?`<button class="secondary" data-accept-handoff="${esc(h.id)}" ${currentUser&&h.toId&&h.toId!==currentUser.id?'disabled':''}>I have taken over care</button>`:''}</article>`).join('')||empty('Prepare a handoff with a snapshot of medication, care notes, and remaining tasks.')}</section>`;}
function familyScreen(){return `<section class="card">${actions('People you care for','<button class="primary" data-new-parent>＋ Add parent</button>')}${familyData.profiles.map(p=>`<div class="entry"><span class="avatar">${esc(p.name.slice(0,2).toUpperCase())}</span><div class="entry-body"><strong>${esc(p.name)}</strong><p>${p.entries.length} journal entries · ${p.medications.filter(m=>m.active).length} active medication plans</p></div><button class="secondary" data-select-parent="${esc(p.id)}">${p.id===activeProfileId?'Selected':'Open profile'}</button></div>`).join('')}</section><section class="card">${actions(currentUser?'Your family account':'Share care with your family')} ${currentUser?`<p>Signed in as <strong>${esc(currentUser.name)}</strong> · ${esc(currentUser.email)}</p><p class="note">Changes sync with this family server. Access follows each member?s assigned role.</p><div class="toolbar">${currentUser.role==='owner'?'<button class="primary" data-invite>Create caregiver invitation</button>':''}<button class="secondary" data-auth="login">Reconnect</button><button class="secondary" data-signout>Sign out</button></div><div id="inviteResult"></div>${members.map(m=>`<div class="entry"><div class="entry-body"><strong>${esc(m.name)}</strong><p>${esc(m.email)} · ${esc(m.role)}</p></div>${currentUser.role==='owner'&&m.id!==currentUser.id?`<button class="text-button" data-remove-member="${esc(m.id)}">Remove access</button>`:''}</div>`).join('')}`:`<p>Sign in to keep care records in sync across your family’s devices.</p><p class="note">${serverAvailable?'Create a family account to upload your local profiles, or use an invitation from your family.':'Open the app through the Kindred server to use accounts. Run Start Kindred.cmd, then open http://localhost:8877.'}</p><div class="toolbar"><button class="primary" data-auth="register" ${serverAvailable?'':'disabled'}>Create account</button><button class="secondary" data-auth="login" ${serverAvailable?'':'disabled'}>Sign in</button></div><label>Your caregiver name for local records<input id="localCaregiver" value="${esc(actor())}" maxlength="80" placeholder="Your name"></label><button class="secondary" data-save-caregiver>Save name</button>`}</section>`;}
render=function(){
  if(['calendar','family'].includes(view)){nav();$('#pageTitle').textContent=view==='calendar'?'A plan for every day.':'Your circle of care.';$('#breadcrumb').textContent=view==='calendar'?'Calendar & Reminders':'Family & Accounts';$('#pageSubtitle').textContent='Care for '+profile().name;$('#content').innerHTML=view==='calendar'?calendarScreen():familyScreen();}
  else {oldRender();if(view==='medication')$('#content').innerHTML=medicationScreen();if(view==='handoff')$('#content').insertAdjacentHTML('beforeend',handoffHistory());if(view==='overview'){const p=profile(),today=Care.dosesOn(p,Care.day()),next=Care.nextDose(p);$('#content').insertAdjacentHTML('afterbegin',`<section class="care-strip"><span><strong>${today.filter(d=>d.record?.status==='taken').length} / ${today.length}</strong> scheduled doses taken today</span><span>${next?'Next dose: '+esc(next.medication.name)+' · '+esc(fmt(next.scheduled)):'No upcoming medication dose'}</span><button class="text-button" data-view="calendar">Open calendar →</button></section>`);}}
  $('#addButton').textContent='＋ Add journal entry';syncStatus();
};
function field(label,name,type='text',value='',extra=''){return `<label>${label}<input type="${type}" name="${name}" value="${esc(value)}" ${extra}></label>`;}
function area(label,name,value='',extra=''){return `<label>${label}<textarea name="${name}" rows="3" ${extra}>${esc(value)}</textarea></label>`;}
function openWorkflow(title,html,onSave,button='Save'){
  const dialog=$('#workflowDialog');dialog.innerHTML=`<form id="workflowForm"><div class="dialog-heading"><h2>${title}</h2><button type="button" class="icon-button" data-close aria-label="Close">✕</button></div>${html}<div id="workflowError" class="form-error" role="alert"></div><div class="dialog-actions"><button type="button" class="secondary" data-close>Cancel</button><button type="submit" class="primary">${button}</button></div></form>`;
  $('#workflowForm').onsubmit=async event=>{event.preventDefault();const form=event.target,submit=form.querySelector('[type=submit]');submit.disabled=true;$('#workflowError').textContent='';try{await onSave(new FormData(form));await KindredStorage.flush();dialog.close();render();}catch(e){$('#workflowError').textContent=e.message;}finally{submit.disabled=false;}};dialog.showModal();
}
function requiredText(d,k){const value=String(d.get(k)||'').trim();if(!value)throw Error('Please complete all required fields.');return value;}
function newMedication(){openWorkflow('Add prescribed medication',field('Medication name','name','text','','required maxlength="120"')+field('Prescribed dose','dosage','text','','required maxlength="100" placeholder="e.g. 1 tablet · 5 mg"')+field('Daily times, separated by commas','times','text','08:00, 20:00','required placeholder="08:00, 20:00"')+'<div class="form-row">'+field('Start date','start','date',Care.day(),'required')+field('End date (optional)','end','date')+'</div>'+area('Instructions from the prescription','instructions','', 'maxlength="2000"')+field('Prescription renewal date (optional)','refill','date'),d=>{const times=[...new Set(requiredText(d,'times').split(',').map(t=>t.trim()))].sort();if(times.some(t=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(t)))throw Error('Use 24-hour times, for example 08:00, 20:00.');const start=d.get('start'),end=d.get('end');if(end&&end<start)throw Error('End date must be on or after the start date.');const m={id:Care.id(),name:requiredText(d,'name'),dosage:requiredText(d,'dosage'),times,start,end,instructions:d.get('instructions').trim(),active:true};profile().medications.push(m);if(d.get('refill'))profile().tasks.push({id:Care.id(),title:'Renew prescription: '+m.name,date:d.get('refill')+'T09:00',assignee:actor(),notes:'Medication: '+m.name,kind:'refill',repeat:'none',completed:[],active:true});persist();toast('Medication plan saved.');});}
function newTask(){openWorkflow('Add a task or reminder',field('Title','title','text','','required maxlength="140"')+'<label>Type<select name="kind"><option value="care">Daily care task</option><option value="refill">Prescription renewal</option><option value="appointment">Appointment reminder</option></select></label>'+field('Date and time','date','datetime-local',localDate(),'required')+'<label>Repeat<select name="repeat"><option value="none">Does not repeat</option><option value="daily">Every day</option><option value="weekly">Every week</option></select></label>'+field('Assigned caregiver','assignee','text',actor(),'maxlength="80"')+area('Notes','notes','','maxlength="2000"'),d=>{profile().tasks.push({id:Care.id(),title:requiredText(d,'title'),date:d.get('date'),repeat:d.get('repeat'),kind:d.get('kind'),assignee:d.get('assignee').trim(),notes:d.get('notes').trim(),completed:[],active:true});persist();toast('Reminder saved.');});}
function doseDialog(id,scheduled){const m=profile().medications.find(m=>m.id===id);openWorkflow('Record administration',`<p>${esc(m.name)} · ${esc(m.dosage)}<br>Scheduled ${esc(fmt(scheduled))}</p><label>Status<select name="status"><option value="taken">Taken</option><option value="skipped">Skipped</option></select></label>`+field('Recorded by','author','text',actor(),'required maxlength="80"'+(currentUser?' readonly':''))+area('Reason (required if skipped)','reason','','maxlength="2000"'),d=>{Care.recordDose(profile(),id,scheduled,d.get('status'),currentUser?.name||requiredText(d,'author'),d.get('reason'));persist();toast('Administration recorded.');});}
function newHandoff(){const options=members.filter(m=>m.id!==currentUser?.id);openWorkflow('Prepare caregiver handoff',field('Handing over from','from','text',actor(),'required maxlength="80"'+(currentUser?' readonly':''))+(currentUser?`<label>Next caregiver<select name="to" required><option value="">Choose a family member</option>${options.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}</select></label>`:field('Next caregiver','to','text','','required maxlength="80"'))+area('What needs special attention?','notes','','maxlength="3000"')+'<p class="note">This saves a dated snapshot of selected notes, medication records, the next dose, and remaining tasks. The next caregiver confirms when they take over.</p>',d=>{const to=requiredText(d,'to'),member=members.find(m=>m.id===to);profile().handoffs.push({id:Care.id(),from:currentUser?.name||requiredText(d,'from'),to:member?.name||to,toId:member?.id||'',createdAt:new Date().toISOString(),summary:handoffText(),notes:d.get('notes').trim(),status:'pending'});persist();toast('Handoff prepared.');},'Prepare handoff');}
function authDialog(mode){const register=mode==='register';openWorkflow(register?'Create your family account':'Welcome back',(register?field('Your name','name','text',actor(),'required maxlength="80" autocomplete="name"'):'')+field('Email','email','email','','required maxlength="254" autocomplete="email"')+field('Password (at least 12 characters)','password','password','','required minlength="12" maxlength="256" autocomplete="'+(register?'new-password':'current-password')+'"')+(register?field('Invitation code (optional)','invite','text','','maxlength="100"')+'<p class="note">Without an invitation, a new family is created with your local profiles. With an invitation, you join that family; your local profiles stay on this device.</p>':field('Authenticator code (if enabled)','otp','text','','inputmode="numeric" maxlength="6"')+'<button type="button" class="text-button" data-reset-password>Forgot password? Use a recovery code</button>'),async d=>{const user=await api(register?'register':'login',{name:d.get('name'),email:d.get('email'),password:d.get('password'),otp:d.get('otp'),invite:d.get('invite'),state:familyData});await attachAccount(user);toast('Connected to your family.');},register?'Create account':'Sign in');}
extras=function(){oldExtras();if($('#categorySelect').value==='vitals')$('#extraFields').innerHTML='<div class="form-row">'+field('Blood pressure: systolic (mmHg)','systolic','number','','min="1" max="400" step="1"')+field('Diastolic (mmHg)','diastolic','number','','min="1" max="300" step="1"')+'</div><div class="form-row">'+field('Pulse (bpm)','pulse','number','','min="1" max="400" step="1"')+field('Temperature (°C)','temperature','number','','min="20" max="50" step="0.1"')+'</div><div class="form-row">'+field('Oxygen saturation (%)','oxygen','number','','min="1" max="100" step="0.1"')+field('Weight (kg)','weight','number','','min="1" max="500" step="0.1"')+'</div>';};
openEntry=function(category,existing){oldOpenEntry(category,existing);$('#entryDialog h2').textContent=existing?'Edit journal entry':'Add journal entry';const f=$('#entryForm');if(currentUser)f.elements.author.value=currentUser.name;else if(!existing&&actor())f.elements.author.value=actor();f.elements.author.readOnly=!!currentUser;if(existing?.vitals)for(const [k,v] of Object.entries(existing.vitals))if(f.elements[k])f.elements[k].value=v;};
$('#categorySelect').onchange=extras;
$('#entryForm').onsubmit=async e=>{e.preventDefault();const f=e.target,d=new FormData(f),id=f.dataset.id,old=profile().entries.find(e=>e.id===id),title=d.get('title').trim(),author=currentUser?.name||d.get('author').trim();if(!title||!author){toast('Enter a title and caregiver name.');return;}const vitals={};for(const k of ['systolic','diastolic','pulse','temperature','oxygen','weight'])if(d.has(k)&&d.get(k)!=='')vitals[k]=Number(d.get(k));if(('systolic'in vitals)!==('diastolic'in vitals)){toast('Enter both blood pressure values.');return;}const item={id:id||Care.id(),category:d.get('category'),title,date:d.get('date'),author,notes:d.get('notes').trim(),handoff:d.has('handoff'),done:old?.done||false,amount:d.has('amount')?Number(d.get('amount')):null,unit:d.get('unit')||'',vitals,updatedBy:author,updatedAt:new Date().toISOString()};if(id)profile().entries[profile().entries.findIndex(e=>e.id===id)]=item;else profile().entries.push(item);f.dataset.id=item.id;if(!persist())return;try{await KindredStorage.flush();}catch(error){let note=f.querySelector('.save-error');if(!note){note=document.createElement('p');note.className='form-error save-error';f.append(note);}note.textContent=error.message;return;}$('#entryDialog').close();render();toast('Entry saved.');};
const oldEntry=entry;
entry=function(e){let result=oldEntry(e);if(e.vitals){const parts=Object.entries(e.vitals).map(([k,v])=>({systolic:'Systolic',diastolic:'Diastolic',pulse:'Pulse',temperature:'Temperature',oxygen:'Oxygen',weight:'Weight'}[k]||k)+': '+v+' '+({systolic:'mmHg',diastolic:'mmHg',pulse:'bpm',temperature:'°C',oxygen:'%',weight:'kg'}[k]||''));if(parts.length)result=result.replace('<p>','<p>'+esc(parts.join(' · '))+'<br>');}return result;};
$('#profileForm').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target);if(!d.get('name').trim())return;Object.assign(profile(),{name:d.get('name').trim(),allergies:d.get('allergies').trim(),emergency:d.get('emergency').trim()});if(!persist())return;try{await KindredStorage.flush();}catch(error){let note=e.target.querySelector('.save-error');if(!note){note=document.createElement('p');note.className='form-error save-error';e.target.append(note);}note.textContent=error.message;return;}$('#profileDialog').close();render();toast('Profile updated.');};
function trend(entries,key,label,unit){const values=entries.filter(e=>Number.isFinite(e.vitals?.[key])).sort((a,b)=>a.date.localeCompare(b.date));if(!values.length)return '';const first=values[0].vitals[key],last=values.at(-1).vitals[key],all=values.map(e=>e.vitals[key]);return `<tr><td>${label}</td><td>${values.length}</td><td>${first} ${unit}<small>${esc(fmt(values[0].date))}</small></td><td>${last} ${unit}<small>${esc(fmt(values.at(-1).date))}</small></td><td>${Math.min(...all)}–${Math.max(...all)} ${unit}</td><td>${last-first>0?'+':''}${Math.round((last-first)*10)/10} ${unit}</td></tr>`;}
report=function(){const from=$('#fromDate').value,to=$('#toDate').value;if(from&&to&&from>to){$('#reportEntries').innerHTML='<p class="form-error">The end date must be on or after the start date.</p>';return;}const inRange=date=>(!from||date.slice(0,10)>=from)&&(!to||date.slice(0,10)<=to),p=profile(),entries=p.entries.filter(e=>inRange(e.date)),doses=p.doses.filter(d=>inRange(d.scheduled));const trends=[['systolic','Systolic blood pressure','mmHg'],['diastolic','Diastolic blood pressure','mmHg'],['pulse','Pulse','bpm'],['temperature','Temperature','°C'],['oxygen','Oxygen saturation','%'],['weight','Weight','kg']].map(k=>trend(entries,...k)).join('');$('#reportEntries').innerHTML=`<div class="report-summary"><div class="eyebrow">CONSULTATION REPORT</div><h2>${esc(p.name)}</h2><p>${from||'First record'} to ${to||'Latest record'} · Generated ${esc(fmt(new Date()))}</p><p><strong>Known allergies:</strong> ${esc(p.allergies||'Not recorded')}<br><strong>Emergency information:</strong> ${esc(p.emergency||'Not recorded')}</p></div><h2>Medication administration</h2><p class="note">${doses.filter(d=>d.status==='taken').length} taken · ${doses.filter(d=>d.status==='skipped').length} skipped. These counts include recorded administrations only; unrecorded doses are not counted as taken or skipped.</p><div class="table-scroll"><table><thead><tr><th>Medication / dose</th><th>Scheduled</th><th>Status</th><th>Recorded by / at</th><th>Reason</th></tr></thead><tbody>${doses.map(d=>`<tr><td>${amountText(d)}</td><td>${esc(fmt(d.scheduled))}</td><td>${esc(d.status)}</td><td>${esc(d.author)}<small>${esc(fmt(d.recordedAt))}</small></td><td>${esc(d.reason)}</td></tr>`).join('')||'<tr><td colspan="5">No administrations in this period.</td></tr>'}</tbody></table></div><h2>Measurement trends</h2><p class="note">Recorded values only. Change compares the first and latest measurement in this period.</p>${trends?`<div class="table-scroll"><table><thead><tr><th>Measurement</th><th>Count</th><th>First</th><th>Latest</th><th>Range</th><th>Change</th></tr></thead><tbody>${trends}</tbody></table></div>`:empty('No structured measurements in this period. Add them under Vital Signs.')}<h2>Symptoms & incidents</h2>${sorted(entries.filter(e=>['symptoms','incidents'].includes(e.category))).map(entry).join('')||empty('No symptoms or incidents recorded in this period.')}<h2>Care journal</h2>${sorted(entries.filter(e=>!['symptoms','incidents'].includes(e.category))).map(entry).join('')||empty('No other journal entries in this period.')}`;};
function exportCalendar(){const p=profile(),events=[];for(let i=0;i<30;i++){const date=Care.addDays(Care.day(),i);for(const d of Care.dosesOn(p,date))if(!d.record)events.push({id:p.id+'-'+d.medication.id+'-'+d.scheduled,date:d.scheduled,title:p.name+': '+d.medication.name+' · '+d.medication.dosage,notes:d.medication.instructions});for(const t of Care.tasksOn(p,date))if(!t.completion)events.push({id:p.id+'-'+t.id+'-'+date,date:t.occurrence,title:p.name+': '+t.title,notes:t.notes+'\nAssigned to: '+t.assignee});for(const e of p.entries.filter(e=>e.category==='appointments'&&!e.done&&e.date.slice(0,10)===date))events.push({id:p.id+'-'+e.id,date:e.date,title:p.name+': '+e.title,notes:e.notes});}download('kindred-calendar.ics',Care.ics(events),'text/calendar');toast('30-day calendar exported with 15-minute reminders.');}
const notified=new Set();
function checkReminders(){if(typeof Notification==='undefined'||Notification.permission!=='granted')return;const now=new Date();for(const p of familyData.profiles){const date=Care.day();const events=[...Care.dosesOn(p,date).filter(d=>!d.record).map(d=>({id:d.medication.id+d.scheduled,date:d.scheduled})),...Care.tasksOn(p,date).filter(t=>!t.completion).map(t=>({id:t.id+t.occurrence,date:t.occurrence})),...p.entries.filter(e=>e.category==='appointments'&&!e.done).map(e=>({id:e.id,date:e.date}))];for(const e of events){const delta=new Date(e.date)-now,key=p.id+e.id;if(delta>=-60000&&delta<=900000&&!notified.has(key)){try{new Notification('Kindred care reminder',{body:'A scheduled care activity is due soon. Open Kindred to review it.',tag:key});notified.add(key);}catch{}}}}}
function selectProfile(id){activeProfileId=id;try{localStorage.setItem('kindred-active-'+(currentUser?.id||'local'),id);}catch{}}
$('#profilePicker').onchange=e=>{selectProfile(e.target.value);render();};
$('#exportButton').onclick=()=>download('kindred-family-backup-'+Care.day()+'.json',JSON.stringify(familyData,null,2),'application/json');
$('#importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10000000)throw Error('Backup is too large.');const imported=Care.migrate(JSON.parse(await file.text()));if(confirm(`Replace all ${familyData.profiles.length} current profiles with ${imported.profiles.length} imported profiles? ${currentUser?'This updates your shared family. ':''}Export a backup first to keep the current records.`)){familyData=imported;activeProfileId=familyData.profiles[0].id;persist();render();toast('Family backup imported.');}}catch(e){toast('Could not import: '+e.message);}finally{$('#importFile').value='';}};
document.addEventListener('change',e=>{if(e.target.id==='doseDate'&&e.target.value){chosenDay.medication=e.target.value;render();}if(e.target.id==='calendarDate'&&e.target.value){chosenDay.calendar=e.target.value;render();}});
document.addEventListener('click',async event=>{
  const b=event.target.closest('button');if(!b)return;
  try{
    if(b.hasAttribute('data-new-medication'))newMedication();
    if(b.dataset.stopMed&&confirm('Stop future doses for this plan? Recorded administrations will remain in the history.')){profile().medications.find(m=>m.id===b.dataset.stopMed).active=false;persist();render();}
    if(b.dataset.dose)doseDialog(b.dataset.dose,b.dataset.at);
    if(b.hasAttribute('data-new-task'))newTask();
    if(b.dataset.taskStop&&confirm('Cancel this reminder and its future repetitions?')){profile().tasks.find(t=>t.id===b.dataset.taskStop).active=false;persist();render();}
    if(b.dataset.taskDone){const id=b.dataset.taskDone,date=b.dataset.day;openWorkflow('Complete care task',field('Completed by','author','text',actor(),'required maxlength="80"'+(currentUser?' readonly':'')),d=>{const task=profile().tasks.find(t=>t.id===id);if(task.completed.some(c=>c.date===date))throw Error('This task has already been completed.');task.completed.push({date,author:currentUser?.name||requiredText(d,'author'),at:new Date().toISOString()});persist();},'Mark completed');}
    if(b.hasAttribute('data-new-handoff'))newHandoff();
    if(b.dataset.acceptHandoff){const h=profile().handoffs.find(h=>h.id===b.dataset.acceptHandoff);openWorkflow('Confirm care takeover',`<p>Handoff from ${esc(h.from)} to ${esc(h.to)}.</p>`+field('Accepting caregiver','author','text',actor()||h.to,'required maxlength="80"'+(currentUser?' readonly':'')),d=>{if(currentUser&&h.toId&&h.toId!==currentUser.id)throw Error('This handoff is assigned to another caregiver.');if(h.status!=='pending')throw Error('This handoff has already been accepted.');h.status='accepted';h.acceptedBy=currentUser?.name||requiredText(d,'author');h.acceptedAt=new Date().toISOString();persist();toast('Care takeover confirmed.');},'I have taken over care');}
    if(b.hasAttribute('data-new-parent'))openWorkflow('Add parent',field('Name','name','text','','required maxlength="80"')+area('Known allergies','allergies','','maxlength="1500"')+area('Emergency information','emergency','','maxlength="2500"'),d=>{const p=Care.freshProfile(requiredText(d,'name'));p.allergies=d.get('allergies').trim();p.emergency=d.get('emergency').trim();familyData.profiles.push(p);activeProfileId=p.id;persist();});
    if(b.dataset.selectParent){selectProfile(b.dataset.selectParent);view='overview';render();}
    if(b.dataset.auth)authDialog(b.dataset.auth);
    if(b.hasAttribute('data-save-caregiver')){localStorage.setItem('kindred-caregiver',$('#localCaregiver').value.trim());toast('Caregiver name saved.');}
    if(b.hasAttribute('data-invite')){const invite=await api('invite',{});$('#inviteResult').innerHTML=`<p class="note">Share this one-use code privately with your caregiver. It expires in ${esc(invite.expiresIn)}. They can create an account at this app’s address using the code.</p><input readonly aria-label="Invitation code" value="${esc(invite.token)}">`;}
    if(b.dataset.removeMember&&confirm('Remove this caregiver’s access and sign them out?')){await api('remove-member',{id:b.dataset.removeMember});members=(await api('members')).members;render();}
    if(b.hasAttribute('data-signout')){if(syncBusy||syncDirty){toast('Sync or export and resolve pending changes before signing out.');return;}await api('logout',{});localStorage.removeItem(cacheKey());currentUser=null;members=[];familyData=localStorage.getItem(LOCAL_KEY)?Care.migrate(JSON.parse(localStorage.getItem(LOCAL_KEY))):{version:2,profiles:[Care.freshProfile()]};activeProfileId=familyData.profiles[0].id;render();}
    if(b.hasAttribute('data-local-copy'))download('kindred-unsynced-'+Date.now()+'.json',JSON.stringify(familyData,null,2),'application/json');
    if(b.hasAttribute('data-load-latest')&&confirm('Load the latest shared version? Download your unsynced version first if you want to keep it.')){const remote=await api('state');Care.validate(remote.state);familyData=remote.state;serverRevision=remote.revision;syncDirty=false;syncConflict=false;syncBase=structuredClone(remote.state);saveCache();$('#syncConflict')?.remove();render();}
    if(b.hasAttribute('data-calendar-export'))exportCalendar();
    if(b.hasAttribute('data-notifications')){if(typeof Notification==='undefined')toast('This browser does not support notifications. Use calendar export.');else{const permission=await Notification.requestPermission();toast(permission==='granted'?'Reminders enabled while this app is open.':'Reminders were not enabled. You can use calendar export.');checkReminders();}}
  }catch(e){toast(e.message);}
});
render();
if(location.protocol!=='file:')api('health').then(async()=>{serverAvailable=true;try{await attachAccount(await api('me'));}catch(e){if(e.status!==401)toast('Could not connect to your family: '+e.message);}render();}).catch(()=>{serverAvailable=false;});
setInterval(()=>refreshFamily(),5000);setInterval(()=>{checkReminders();if(!document.querySelector('dialog[open]')&&['overview','medication','calendar'].includes(view))render();},30000);
window.addEventListener('beforeunload',event=>{if(syncDirty){event.preventDefault();event.returnValue='';}});
