(()=>{
 const previousNav=nav,previousRender=render;
 nav=function(){previousNav();$('#navigation').insertAdjacentHTML('beforeend',navItem(['guide','User Guide','?']));$('#mobileNavigation')?.insertAdjacentHTML('beforeend','<option value="guide">User Guide</option>');if(view==='guide')$('#mobileNavigation').value='guide';};
 function block(b){return `<h3>${esc(b.title)}</h3>${b.text?`<p>${esc(b.text)}</p>`:''}${b.steps?`<ol>${b.steps.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>`:''}${b.bullets?`<ul>${b.bullets.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:''}`;}
 render=function(){const selected=view;if(view==='guide')view='overview';previousRender();view=selected;$('#addButton').hidden=view==='guide';if(view!=='guide')return;nav();document.body.dataset.view='guide';$('#pageTitle').textContent='Your Kindred user guide';$('#breadcrumb').textContent='User Guide';$('#pageSubtitle').textContent='Step-by-step help for everyday care. Available offline after the app has loaded.';
  $('#content').innerHTML=`<section class="card guide-intro"><div><div class="eyebrow">${esc(KindredGuide.edition)}</div><h2>${esc(KindredGuide.subtitle)}</h2><p>Search a topic or open a chapter below. The PDF contains the same instructions.</p></div><a class="secondary" href="output/pdf/Kindred-User-Guide.pdf" download="Kindred-User-Guide.pdf">Download PDF</a></section><section class="card"><label>Search the manual<input type="search" id="guideSearch" placeholder="Try photo, backup, medication or install"></label><p id="guideCount" class="note" role="status">${KindredGuide.sections.length} chapters</p><div class="guide-chapters">${KindredGuide.sections.map((s,i)=>`<details class="guide-chapter"><summary><span>${String(i+1).padStart(2,'0')}</span>${esc(s.title)}</summary><div class="guide-body"><p class="guide-lead">${esc(s.intro)}</p>${s.blocks.map(block).join('')}</div></details>`).join('')}</div></section>`;
 };
 document.addEventListener('input',e=>{if(e.target.id!=='guideSearch')return;const query=e.target.value.trim().toLowerCase();let count=0;document.querySelectorAll('.guide-chapter').forEach(ch=>{ch.hidden=!!query&&!ch.textContent.toLowerCase().includes(query);if(!ch.hidden)count++;if(query)ch.open=!ch.hidden;else ch.open=false;});$('#guideCount').textContent=count?`${count} matching chapters`:'No chapters match. Try another word.';});
 render();
})();
