/* Guided local workflows. Existing storage, permissions and audit remain in use. */
(()=>{
 const P=KindredPremium,priorRender=render,priorNav=nav,priorReport=report,priorSettings=settingsScreen,priorHandoff=handoffText;
 const baseLocalChanges=localChanges;localChanges=function(before,after){const rows=baseLocalChanges(before,after);for(const p of after.profiles){const old=before.profiles.find(x=>x.id===p.id);if(!old)continue;const meta=x=>({name:x.name,allergies:x.allergies,emergency:x.emergency,careDetails:{...x.careDetails,photo:x.careDetails?.photo?'[Profile photo]':''}});if(JSON.stringify({...old,entries:[],medications:[],doses:[],tasks:[],handoffs:[],shifts:[],questions:[]})!==JSON.stringify({...p,entries:[],medications:[],doses:[],tasks:[],handoffs:[],shifts:[],questions:[]}))rows.push({id:Care.id(),profile:p.id,collection:'profile details',record:p.id,before:meta(old),after:meta(p),action:'updated',actor:actor()||'Local caregiver',at:new Date().toISOString(),reason:pendingReason});}return rows;};
 const filters={query:'',category:'',author:'',from:'',to:'',handoff:false};let reportMode='full',agendaFilter='all';
 const safeGet=(key,fallback='')=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}};
 const safeSet=(key,value)=>{try{localStorage.setItem(key,value);}catch{toast('This browser could not remember that preference.');}};
 const person=()=>profile().careDetails||{};
 async function commit(action,message){if(!editingAllowed())throw Error('Switch to an editable care profile first.');if(profile().isDemo){const before=structuredClone(profile());try{action();persist();await KindredStorage.flush();toast(message);return;}catch(error){KindredDemo.restore(before);throw error;}}const before=structuredClone(familyData),baseline=structuredClone(previousLocal),history=safeGet('kindred-local-history','[]');try{reasonForChange(message);action();Care.validate(familyData);if(!persist())throw Error(lastSaveError||'The profile could not be saved. Your form is still open; check your current editing access and try again.');await KindredStorage.flush();}catch(error){familyData=before;previousLocal=baseline;if(!currentUser)safeSet('kindred-local-history',history);saveCache();throw error;}toast(message);}
 nav=function(){priorNav();$('#navigation').insertAdjacentHTML('afterbegin',navItem(['today','Today','☀']));$('#navigation').insertAdjacentHTML('beforeend',navItem(['search-all','Search records','⌕']));const select=$('#mobileNavigation');if(select){select.insertAdjacentHTML('afterbegin','<option value="today">Today</option>');select.insertAdjacentHTML('beforeend','<option value="search-all">Search records</option>');select.value=view;}};
 function quickTools(){return `<section class="card quick-capture"><div class="card-head"><div><div class="eyebrow">A FEW TAPS, A USEFUL UPDATE</div><h2>Quick record</h2></div><span class="badge">Review before saving</span></div><div class="capture-grid">${[['water','Water','◡'],['meal','Meal','◒'],['mood','Mood','☺'],['sleep','Sleep','☾'],['vitals','Vital signs','♡'],['note','Care note','✎']].map(([id,name,icon])=>`<button class="secondary" data-premium-quick="${id}" ${editingAllowed()?'':'disabled'}><span aria-hidden="true">${icon}</span>${name}</button>`).join('')}</div><p class="note">Medication administration is recorded against the prescription schedule in Today.</p></section>`;}
 function agendaRows(){const rows=P.agenda(profile()),shown=rows.filter(r=>agendaFilter==='all'||r.status===agendaFilter);return `<p class="note">${rows.filter(r=>r.status==='needs-record').length} need a record · ${rows.filter(r=>r.status==='upcoming').length} upcoming · ${rows.filter(r=>r.status==='recorded').length} recorded. An unrecorded activity does not establish whether care was provided.</p>`+(shown.map(r=>{
   const assigned=r.kind==='medication'?members.find(m=>m.id===r.assignee)?.name||'Unassigned':r.assignee||'Unassigned';
   let button='';if(r.status==='needs-record'&&editingAllowed())button=r.kind==='medication'?`<button class="secondary" data-dose="${esc(r.id)}" data-at="${esc(r.date)}">Record dose</button>`:r.kind==='task'?`<button class="secondary" data-task-done="${esc(r.id)}" data-day="${esc(r.date.slice(0,10))}">Complete</button>`:`<button class="secondary" data-done="${esc(r.id)}">Mark complete</button>`;
   return `<article class="agenda-row"><div class="agenda-time"><strong>${esc(r.date.slice(11,16))}</strong><small>${r.date.slice(0,10)===Care.day()?'Today':esc(r.date.slice(0,10))}</small></div><div class="entry-body"><strong>${esc(r.title)}</strong><p>${esc(r.detail)}</p><small>${esc(r.kind)} · ${esc(assigned)}</small></div><span class="badge ${r.status==='needs-record'?'warning':''}">${r.status==='needs-record'?'Needs a record':r.status==='upcoming'?'Upcoming':esc(r.result)}</span>${button}</article>`;
  }).join('')||empty('Nothing in this view. Plan medication in Medication Log, or add a task in Calendar & Reminders.'));}
 function todayScreen(){const shifts=(profile().shifts||[]).filter(s=>new Date(s.start)<=new Date()&&new Date(s.end)>new Date());return `<section class="card"><div class="card-head"><div><div class="eyebrow">${esc(Care.day())}</div><h2>Today’s care plan</h2></div><button class="secondary" data-view="calendar">Plan an activity</button></div><p>${shifts.length?'On duty: '+shifts.map(s=>esc(s.caregiver)+' until '+esc(s.end.slice(11,16))+(s.backup?' · Backup: '+esc(s.backup):'')).join('<br>'):'No caregiver shift is scheduled right now.'}</p><label>Show<select id="agendaFilter">${[['all','All activities'],['needs-record','Needs a record'],['upcoming','Upcoming'],['recorded','Recorded']].map(([v,label])=>`<option value="${v}" ${v===agendaFilter?'selected':''}>${label}</option>`).join('')}</select></label><div id="agendaRows">${agendaRows()}</div></section>${quickTools()}`;}
 function setupCard(){const d=person(),items=[['Name',profile().name!=='Parent'],['Emergency information',!!profile().emergency],['Care preferences',!!d.preferences],['Routine',!!d.routine],['Care goals',!!d.goals]],n=items.filter(x=>x[1]).length;return `<section class="card setup-card"><div><div class="eyebrow">MAKE THIS SPACE YOURS · ${n}/${items.length}</div><h2>${n===5?'Your care profile is ready':'A thoughtful start to everyday care'}</h2><p class="note">${items.map(([label,done])=>(done?'✓ ':'○ ')+label).join(' · ')}</p></div><button class="secondary" data-premium-setup ${editingAllowed()?'':'disabled'}>${n===5?'Review setup':'Set up care profile'}</button></section>`;}
 function profileFields(){const d=person();return field('Preferred name','preferredName','text',d.preferredName||'','maxlength="80"')+area('Likes, dislikes and care preferences','preferences',d.preferences||'','maxlength="2000"')+area('Usual daily routine','routine',d.routine||'','maxlength="3000"')+area('Goals agreed with the family or clinician','goals',d.goals||'','maxlength="2000"')+area('Communication and accessibility needs','communication',d.communication||'','maxlength="1500"');}
 function photoField(){return '<label>Profile photo (optional · JPEG or PNG, up to 5 MB)<input name="photo" type="file" accept="image/jpeg,image/png"></label><div class="profile-photo-preview" hidden><img alt="Selected profile photo preview"><span>Photo preview</span></div><p class="note">The photo is cropped to a square and saved with this parent’s profile.</p>';}
 function deleteParent(id){
  if(!editingAllowed())return;const target=familyData.profiles.find(p=>p.id===id);if(!target)return;
  const count=['entries','medications','doses','tasks','handoffs','shifts','questions'].reduce((n,k)=>n+(target[k]?.length||0),0);
  openWorkflow('Delete parent profile',`<p>Delete <strong>${esc(target.name)}</strong> and ${count} associated care records, including the profile photo?</p><p>This removes the profile from your active family data${currentUser?' and syncs the removal to the family server':''}. Existing backups and server audit history are retained. Attached server files are not erased by this action.</p>${familyData.profiles.length===1?'<p>A new empty Parent profile will be created so you can keep using Kindred.</p>':''}<button type="button" class="secondary" data-premium-backup>Download backup first</button>${field('Type the parent’s exact name to confirm','confirmation','text','','required autocomplete="off"')}`,async d=>{
   if(d.get('confirmation')!==target.name)throw Error('The name does not match. Nothing was deleted.');
   if(!familyData.profiles.some(p=>p.id===id))throw Error('This profile no longer exists.');
   const selected=activeProfileId;try{await commit(()=>{familyData.profiles=familyData.profiles.filter(p=>p.id!==id);if(!familyData.profiles.length)familyData.profiles.push(Care.freshProfile());if(activeProfileId===id)activeProfileId=familyData.profiles[0].id;},'Parent profile removed.');selectProfile(activeProfileId);}catch(error){activeProfileId=selected;throw error;}
  },'Delete profile');
 }
 function photoPreview(current=''){const form=$('#workflowForm'),input=form.elements.photo,preview=form.querySelector('.profile-photo-preview');let generation=0;const show=src=>{preview.hidden=!src;if(src)preview.querySelector('img').src=src;else preview.querySelector('img').removeAttribute('src');};show(current);input.onchange=async()=>{const token=++generation;show('');$('#workflowError').textContent='';const file=input.files[0];if(!file){show(current);return;}try{const photo=await resizePhoto(file);if(token===generation&&form.isConnected)show(photo);}catch(error){if(token===generation&&form.isConnected)$('#workflowError').textContent=error.message;}};}
 function newParentWithPhoto(){openWorkflow('Add parent',field('Name','name','text','','required maxlength="80"')+photoField()+area('Known allergies','allergies','','maxlength="1500"')+area('Emergency information','emergency','','maxlength="2500"'),async data=>{const name=requiredText(data,'name'),file=data.get('photo'),photo=file?.size?await resizePhoto(file):'',selected=activeProfileId;try{await commit(()=>{const p=Care.freshProfile(name);p.allergies=data.get('allergies').trim();p.emergency=data.get('emergency').trim();p.careDetails={photo};familyData.profiles.push(p);activeProfileId=p.id;},'Parent profile saved.');selectProfile(activeProfileId);}catch(error){activeProfileId=selected;throw error;}});photoPreview();}
 document.addEventListener('click',event=>{if(!event.target.closest('[data-new-parent]')||!editingAllowed())return;event.preventDefault();event.stopImmediatePropagation();newParentWithPhoto();},true);
 function detailsDialog(){openWorkflow('Personal care preferences',profileFields()+photoField()+'<label class="checkbox"><input name="removePhoto" type="checkbox">Remove current photo</label><p class="note">The photo is included in family backups.</p>',async data=>{let photo=person().photo||'';if(data.get('removePhoto'))photo='';const file=data.get('photo');if(file?.size)photo=await resizePhoto(file);const details=Object.fromEntries(Object.keys(P.limits).map(k=>[k,String(data.get(k)||'').trim()]));await commit(()=>{profile().careDetails={...details,photo};},'Care preferences saved.');});photoPreview(person().photo||'');}
 async function resizePhoto(file){if(!['image/jpeg','image/png'].includes(file.type)||file.size>5*1024*1024)throw Error('Choose a JPEG or PNG smaller than 5 MB.');const url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not read photo.'));reader.readAsDataURL(file);});try{const img=new Image();img.src=url;await img.decode();if(!img.width||!img.height)throw Error('This image could not be read.');const canvas=document.createElement('canvas');canvas.width=canvas.height=240;const ctx=canvas.getContext('2d'),side=Math.min(img.width,img.height);ctx.drawImage(img,(img.width-side)/2,(img.height-side)/2,side,side,0,0,240,240);return canvas.toDataURL('image/jpeg',.82);}finally{URL.revokeObjectURL(url);}}
 function setup(){openWorkflow('Set up your care space',`<p class="wizard-progress" id="wizardProgress">Step 1 of 3 · The people</p><section data-step="0">${field('Parent’s name','name','text',profile().name==='Parent'?'':profile().name,'required maxlength="80"')}${currentUser?'':field('Your caregiver name','caregiver','text',actor(),'required maxlength="80"')}</section><section data-step="1" hidden>${area('Known allergies','allergies',profile().allergies,'maxlength="1500"')}${area('Emergency contacts and important information','emergency',profile().emergency,'maxlength="2500"')}<p class="note">You can leave unknown details empty and add them later.</p></section><section data-step="2" hidden>${profileFields()}<p class="note">Medication plans can be added afterwards using the actual prescription.</p></section><div class="wizard-navigation"><button type="button" class="secondary" id="wizardBack" hidden>Back</button><button type="button" class="primary" id="wizardNext">Continue</button></div>`,async d=>{
  await commit(()=>{Object.assign(profile(),{name:requiredText(d,'name'),allergies:d.get('allergies').trim(),emergency:d.get('emergency').trim(),careDetails:{...person(),...Object.fromEntries(Object.keys(P.limits).map(k=>[k,String(d.get(k)||'').trim()]))}});},'Care space configured.');if(!currentUser)safeSet('kindred-caregiver',requiredText(d,'caregiver'));
 },'Finish setup');let step=0;const form=$('#workflowForm'),submit=form.querySelector('[type=submit]');submit.hidden=true;
  function show(){form.querySelectorAll('[data-step]').forEach(el=>el.hidden=Number(el.dataset.step)!==step);$('#wizardProgress').textContent=`Step ${step+1} of 3 · ${['The people','Essential information','Everyday preferences'][step]}`;$('#wizardBack').hidden=step===0;$('#wizardNext').hidden=step===2;submit.hidden=step!==2;form.querySelector(`[data-step="${step}"] input, [data-step="${step}"] textarea`)?.focus();}
  $('#wizardNext').onclick=()=>{for(const input of form.querySelectorAll(`[data-step="${step}"] input`))if(!input.reportValidity())return;step++;show();};$('#wizardBack').onclick=()=>{step--;show();};form.addEventListener('submit',e=>{if(step<2){e.preventDefault();e.stopImmediatePropagation();$('#wizardNext').click();}},true);
 }
 function quick(kind){
  if(['water','meal','mood','sleep'].includes(kind)){
   const config={water:['meals','Water intake'],meal:['meals','Meal update'],mood:['mood','Mood check-in'],sleep:['sleep','Sleep update']}[kind];
   const input=kind==='water'?field('Amount consumed (ml)','value','number','','required min="1" max="5000" step="1"'):kind==='sleep'?field('Hours slept','value','number','','required min="0" max="24" step="0.25"'):`<label>${kind==='meal'?'Amount eaten':'Observed mood'}<select name="value">${(kind==='meal'?['All','Most','Half','A little','None']:['Calm','Content','Tired','Anxious','Restless','Low mood','Other']).map(v=>`<option>${v}</option>`).join('')}</select></label>`;
   openWorkflow(config[1],input+field('Recorded by','author','text',actor(),'required maxlength="80"'+(currentUser?' readonly':''))+field('Date and time','date','datetime-local',localDate(),'required')+area('Optional observation','notes','','maxlength="3000"')+'<label class="checkbox"><input type="checkbox" name="handoff">Include in caregiver handoff</label>',async d=>{
    const date=d.get('date'),value=d.get('value');if(new Date(date)>new Date())throw Error('Choose a time that has already occurred.');
    if(['water','sleep'].includes(kind)&&(!Number.isFinite(Number(value))||Number(value)<(kind==='water'?1:0)||Number(value)>(kind==='water'?5000:24)))throw Error('Enter a valid amount.');
    const author=currentUser?.name||requiredText(d,'author');await commit(()=>profile().entries.push({id:Care.id(),category:config[0],title:config[1],date,author,notes:(kind==='meal'?'Amount eaten: '+value:kind==='mood'?'Observed mood: '+value:'')+(d.get('notes').trim()?'\n'+d.get('notes').trim():''),handoff:d.has('handoff'),done:false,amount:['water','sleep'].includes(kind)?Number(value):null,unit:kind==='water'?'ml':kind==='sleep'?'hours':'',updatedBy:author,updatedAt:new Date().toISOString()}),'Care update saved.');
   },'Save update');return;
  }
  const templates={water:['meals','Water intake','Amount consumed: ___ ml'],meal:['meals','Meal update','Meal: ___\nAmount eaten: ___\nNotes: '],mood:['mood','Mood check-in','Observed mood: ___\nContext: '],sleep:['sleep','Sleep update','Fell asleep: ___\nWoke up: ___\nInterruptions: '],vitals:['vitals','Vital signs',''],note:['daily','Care update','']};const t=templates[kind];if(!t)return;openEntry(t[0]);const f=$('#entryForm');f.elements.title.value=t[1];f.elements.notes.value=t[2];f.elements.notes.focus();}
 function searchScreen(){return `<section class="card"><div class="card-head"><h2>Search this care profile</h2><span class="badge">All journal categories</span></div><div class="search-filters">${field('Search title, notes or caregiver','query','search',filters.query,'id="globalQuery"') }<label>Category<select id="globalCategory"><option value="">All categories</option>${categories.map(c=>`<option value="${c[0]}" ${filters.category===c[0]?'selected':''}>${c[1]}</option>`).join('')}</select></label>${field('From','from','date',filters.from,'id="globalFrom"')}${field('To','to','date',filters.to,'id="globalTo"')}<label>Caregiver<select id="globalAuthor"><option value="">All caregivers</option>${[...new Set(profile().entries.map(e=>e.author))].sort().map(a=>`<option ${filters.author===a?'selected':''}>${esc(a)}</option>`).join('')}</select></label><label class="checkbox"><input type="checkbox" id="globalHandoff" ${filters.handoff?'checked':''}>Handoff entries only</label></div><button class="text-button" data-premium-clear>Clear filters</button><p class="note" id="searchCount" role="status"></p><div id="globalResults"></div></section>`;}
 function searchResults(){if(!$('#globalResults'))return;if(filters.from&&filters.to&&filters.from>filters.to){$('#searchCount').textContent='The end date must be on or after the start date.';$('#globalResults').innerHTML='';return;}const matches=P.search(profile(),filters);$('#searchCount').textContent=`${matches.length} matching records${matches.length>200?' · Showing the first 200. Narrow the filters to see more.':''}`;$('#globalResults').innerHTML=matches.slice(0,200).map(entry).join('')||empty('No matches. Try another date, caregiver or search term.');readonly();}
 function readonly(){if(editingAllowed())return;$('#content').querySelectorAll('[data-dose],[data-task-done],[data-done],[data-edit],[data-delete],[data-premium-quick],[data-premium-setup],[data-premium-profile]').forEach(b=>b.disabled=true);}
 function careCard(){const d=person();return card('Personal care guide',`<div class="card-head"><p class="note">Preferences, routines and goals for ${esc(d.preferredName||profile().name)}.</p><button class="secondary" data-premium-profile ${editingAllowed()?'':'disabled'}>Edit preferences & photo</button></div>${Object.entries({preferences:'Preferences',routine:'Daily routine',goals:'Care goals',communication:'Communication needs'}).map(([k,label])=>`<h2>${label}</h2><p class="care-prose">${esc(d[k]||'Not added yet.')}</p>`).join('')}`);}
 handoffText=function(){const p=profile(),details=p.careDetails||{},outstanding=P.agenda(p).filter(r=>r.status!=='recorded'&&r.date.slice(0,10)<Care.day());return priorHandoff()+'\n\nCare preferences\n'+(details.preferences||'Not recorded.')+'\n\nRoutine and communication\n'+[details.routine,details.communication].filter(Boolean).join('\n')+'\n\nEarlier activities still awaiting a record\n'+(outstanding.map(r=>`${r.title} · ${fmt(r.date)} · ${r.status==='needs-record'?'Needs a record':'Upcoming'}`).join('\n')||'None.')+'\n\nCare goals\n'+(details.goals||'Not recorded.');};
 report=function(){
  if(reportMode==='full'){priorReport();if(!$('#reportEntries .form-error'))$('#reportEntries').insertAdjacentHTML('afterbegin',`<section class="report-preferences"><h2>Personal care guide</h2><p class="care-prose">${esc([person().preferences,person().routine,person().goals,person().communication].filter(Boolean).join('\n')||'No care preferences recorded.')}</p></section>`);return;}
  const from=$('#fromDate').value,to=$('#toDate').value,p=profile();if(from&&to&&from>to){$('#reportEntries').innerHTML='<p class="form-error">The end date must be on or after the start date.</p>';return;}
  const entries=P.search(p,{from,to}),doses=p.doses.filter(d=>(!from||d.scheduled.slice(0,10)>=from)&&(!to||d.scheduled.slice(0,10)<=to));
  $('#reportEntries').innerHTML=`<section class="visit-cover"><div class="eyebrow">KINDRED · CONSULTATION BRIEF</div><h2>${esc(p.name)}</h2><p>${esc(from||'First record')} to ${esc(to||'Latest record')} · Prepared ${esc(fmt(new Date()))}</p><p><strong>Allergies:</strong> ${esc(p.allergies||'Not recorded')}</p><p class="care-prose"><strong>Emergency information:</strong> ${esc(p.emergency||'Not recorded')}</p></section><h2>Medication plans currently active</h2>${p.medications.filter(m=>m.active).map(m=>`<p>${esc(m.name)} · ${esc(m.dosage)} · ${esc(m.times.join(', '))}<br>${esc(m.instructions)}</p>`).join('')||'<p>No active plans recorded.</p>'}<p class="note">In selected period: ${doses.filter(d=>d.status==='taken').length} administrations taken; ${doses.filter(d=>d.status==='skipped').length} skipped. Active plans reflect the current profile, not a historical prescription list.</p><h2>Questions to discuss</h2>${(p.questions||[]).filter(q=>q.status==='open').map(q=>`<p>□ ${esc(q.title)}</p>`).join('')||'<p>No open questions.</p>'}<h2>Care goals and preferences</h2><p class="care-prose">${esc([person().goals,person().preferences].filter(Boolean).join('\n')||'Not recorded.')}</p><h2>Symptoms, incidents and measurements</h2>${entries.filter(e=>['symptoms','incidents','vitals'].includes(e.category)).map(entry).join('')||'<p>No records in this period.</p>'}<p class="note">Prepared from family-entered records. This report does not interpret measurements or recommend treatment.</p>`;
 };
 settingsScreen=function(){return priorSettings()+card('Privacy when you step away',`<label>Hide records after inactivity<select id="privacyDelay">${[['0','Off'],['1','1 minute'],['5','5 minutes'],['15','15 minutes']].map(([v,t])=>`<option value="${v}" ${safeGet('kindred-privacy-delay','0')===v?'selected':''}>${t}</option>`).join('')}</select></label><button class="secondary" data-premium-privacy>Hide records now</button><p class="note">This privacy screen prevents casual viewing. It is not a password lock or encryption. Use your device’s screen lock for access protection.</p>`)+card('Backup & recovery check',`<p>${safeGet('kindred-backup-request')?'Last backup download requested: '+esc(fmt(safeGet('kindred-backup-request'))):'No backup download has been requested from this browser yet.'}</p><p class="note">Keep a backup outside this browser. Clearing browser data can remove local records. A download request does not confirm that the file was saved.</p><div class="toolbar"><button class="secondary" data-premium-backup ${profile().isDemo?'disabled':''}>Download family backup</button><button class="secondary" data-premium-check-backup>Check a backup file</button><button class="text-button" data-view="history">Open recovery history</button></div>`);};
 const oldHistory=historyScreen;historyScreen=function(){return '<section class="card"><label>Filter change history<input type="search" id="historySearch" placeholder="Caregiver, action, reason or changed detail"></label></section>'+oldHistory();};
 const oldExport=$('#exportButton').onclick;$('#exportButton').onclick=()=>{if(profile().isDemo)return;oldExport();safeSet('kindred-backup-request',new Date().toISOString());};
 function checkBackup(){openWorkflow('Check a family backup','<label>Kindred JSON backup<input type="file" name="backup" accept="application/json,.json" required></label><p class="note">Checks the file without importing or changing your records. Attached server documents are stored in the encrypted server backup, not the JSON family backup.</p>',async d=>{const f=d.get('backup');if(f.size>10000000)throw Error('Backup is too large.');const data=Care.migrate(JSON.parse(await f.text()));Care.validate(data);const counts=`${data.profiles.length} profiles and ${data.profiles.reduce((n,p)=>n+p.entries.length,0)} journal entries`;setTimeout(()=>openWorkflow('Backup checked',`<p>Valid Kindred structure: <strong>${counts}</strong>.</p><p>No records were imported. Use Import when you want to replace current family records, after keeping a backup of those records.</p>`,()=>{},'Done'),0);},'Check backup');}
 const privacy=document.createElement('dialog');privacy.id='privacyScreen';privacy.innerHTML='<div class="privacy-content"><span aria-hidden="true">♡</span><h2>Your care space is paused</h2><p>Records are hidden while you step away.</p><button class="primary" id="resumeCare">Resume care</button><p class="note">Privacy screen · no password protection</p></div>';document.body.append(privacy);
 let lastActivity=Date.now(),returnFocus=null;
 function hideRecords(){if(privacy.open)return;returnFocus=document.activeElement;privacy.showModal();document.body.classList.add('privacy-paused');$('#resumeCare').focus();}
 function resume(){privacy.close();document.body.classList.remove('privacy-paused');lastActivity=Date.now();returnFocus?.focus();}
 $('#resumeCare').onclick=resume;privacy.addEventListener('cancel',e=>e.preventDefault());
 ['pointerdown','keydown','input','scroll'].forEach(type=>document.addEventListener(type,()=>{if(!privacy.open)lastActivity=Date.now();},{passive:true,capture:true}));
 setInterval(()=>{const minutes=Number(safeGet('kindred-privacy-delay','0'));if(minutes>0&&Date.now()-lastActivity>=minutes*60000)hideRecords();},1000);
 render=function(){
  // Legacy renderers only know their own views; render a stable base before custom screens.
  const selected=view;if(['today','search-all'].includes(view))view='overview';priorRender();view=selected;
  if(['today','search-all'].includes(view)){nav();$('#pageTitle').textContent=view==='today'?'Today, together.':'Find the details that matter.';$('#breadcrumb').textContent=view==='today'?'Today':'Search records';$('#pageSubtitle').textContent='Care for '+profile().name;$('#content').innerHTML=view==='today'?todayScreen():searchScreen();}
  document.body.dataset.view=view;
  if(view==='overview'){$('#content').insertAdjacentHTML('afterbegin',setupCard());$('.hero-links [data-view="calendar"]')?.setAttribute('data-view','today');$('.insight-grid')?.insertAdjacentHTML('afterend',quickTools());}
  if(view==='family')$('#content').insertAdjacentHTML('afterbegin',careCard());
  if(view==='settings')$('#content').insertAdjacentHTML('afterbegin',setupCard());
  if(view==='reports'){
   $('.toolbar').insertAdjacentHTML('beforeend',`<label>Report format<select id="reportMode"><option value="full" ${reportMode==='full'?'selected':''}>Full care report</option><option value="brief" ${reportMode==='brief'?'selected':''}>Consultation brief</option></select></label><button class="secondary" data-premium-period="7">Last 7 days</button><button class="secondary" data-premium-period="30">Last 30 days</button><button class="text-button" data-premium-period="all">All dates</button>`);
  }
  if(view==='search-all')searchResults();
  if(person().photo){const avatar=$('#profileButton .avatar');avatar.innerHTML=`<img src="${esc(person().photo)}" alt="${esc(profile().name)}">`;}
  else {const avatar=$('#profileButton .avatar');avatar.textContent=profile().name.replace(/^Demo · /,'').split(/\s+/).slice(0,2).map(w=>w[0]).join('').toUpperCase();}
  if(view==='family')document.querySelectorAll('[data-select-parent]').forEach(button=>{const p=familyData.profiles.find(p=>p.id===button.dataset.selectParent),avatar=button.closest('.entry')?.querySelector('.avatar');if(avatar&&p?.careDetails?.photo)avatar.innerHTML=`<img src="${esc(p.careDetails.photo)}" alt="${esc(p.name)}">`;if(editingAllowed())button.insertAdjacentHTML('afterend',`<button class="text-button" data-premium-delete-parent="${esc(p.id)}">Delete profile</button>`);});
  readonly();
 };
 document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;try{
  if(b.hasAttribute('data-premium-setup')&&editingAllowed())setup();
  if(b.hasAttribute('data-premium-profile')&&editingAllowed())detailsDialog();
  if(b.dataset.premiumQuick&&editingAllowed())quick(b.dataset.premiumQuick);
  if(b.hasAttribute('data-premium-clear')){Object.keys(filters).forEach(k=>filters[k]=k==='handoff'?false:'');render();}
  if(b.hasAttribute('data-premium-privacy'))hideRecords();
  if(b.hasAttribute('data-premium-backup'))$('#exportButton').click();
  if(b.hasAttribute('data-premium-check-backup'))checkBackup();
  if(b.dataset.premiumDeleteParent)deleteParent(b.dataset.premiumDeleteParent);
  if(b.dataset.premiumPeriod){$('#fromDate').value=b.dataset.premiumPeriod==='all'?'':Care.addDays(Care.day(),1-Number(b.dataset.premiumPeriod));$('#toDate').value=b.dataset.premiumPeriod==='all'?'':Care.day();report();}
 }catch(error){toast(error.message);}});
 document.addEventListener('input',e=>{if(e.target.id==='historySearch'){const query=e.target.value.toLowerCase();document.querySelectorAll('.history-record').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(query));}if(e.target.id==='globalQuery'){filters.query=e.target.value;searchResults();}});
 document.addEventListener('change',e=>{const id=e.target.id,map={globalCategory:'category',globalFrom:'from',globalTo:'to',globalAuthor:'author',globalHandoff:'handoff'};if(map[id]){filters[map[id]]=id==='globalHandoff'?e.target.checked:e.target.value;searchResults();}if(id==='agendaFilter'){agendaFilter=e.target.value;$('#agendaRows').innerHTML=agendaRows();}if(id==='reportMode'){reportMode=e.target.value;report();readonly();}if(id==='privacyDelay'){safeSet('kindred-privacy-delay',e.target.value);lastActivity=Date.now();}});
 setInterval(()=>{if(view==='today'&&!document.querySelector('dialog[open]')){const rows=$('#agendaRows');if(rows)rows.innerHTML=agendaRows();}},30000);
 // A consistent outlined icon family, without external icon requests.
 const paths={today:'M12 3v2m0 14v2M3 12h2m14 0h2M5.6 5.6 7 7m10 10 1.4 1.4M5.6 18.4 7 17M17 7l1.4-1.4M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',calendar:'M4 5h16v16H4zM4 10h16M8 3v4m8-4v4',handoff:'M4 7h15l-4-4M20 17H5l4 4',emergency:'M9 3h6v6h6v6h-6v6H9v-6H3V9h6z',reports:'M5 3h14v18H5zM8 8h8M8 12h8M8 16h5',family:'M16 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-3a8 8 0 0 1 16 0v3',shifts:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M12 6v6l4 2',consultation:'m4 17-1 4 4-1L20 7l-4-4zM13 6l5 5',history:'M4 9a8 8 0 1 1 0 7M4 3v6h6M12 8v5l3 2',settings:'M20 12a8 8 0 1 1-16 0 8 8 0 0 1 16 0M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0','search-all':'M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0m-2 5 6 6'};
 const categoryPaths={medication:'m8 4 12 12a4 4 0 0 1-6 6L2 10a4 4 0 0 1 6-6m-2 10 6-6',appointments:paths.calendar,vitals:'M2 12h5l3-8 4 16 3-8h5',symptoms:'M3 12h5l3-6 4 12 3-6h3',meals:'M5 3v7m3-7v7m3-7v7M5 7h6M8 10v11M18 3v18m0-18c-4 3-4 9 0 9',daily:paths.today,mood:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M8 9h.01M16 9h.01M8 15q4 4 8 0',sleep:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11',incidents:'m12 3 10 18H2zM12 9v5m0 3h.01',doctor:paths.consultation,expenses:'M20 7H8a4 4 0 0 0 0 8h8a4 4 0 0 1 0 8H4M12 3v20',team:paths.family,documents:paths.reports};
 const svg=path=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"/></svg>`;
 const baseEntry=entry;entry=function(e){return baseEntry(e).replace(/(<span class="entry-icon">)[\s\S]*?(<\/span>)/,(_,a,b)=>a+svg(categoryPaths[e.category]||paths.reports)+b);};
 const finalNav=nav;nav=function(){finalNav();document.querySelectorAll('nav button[data-view]').forEach(b=>{const target=b.querySelector('.nav-icon'),path=paths[b.dataset.view];if(target&&path)target.innerHTML=svg(path);if(b.dataset.view===view)b.setAttribute('aria-current','page');});};
 render();
})();
